package com.hand.hmall.hr.dto;

/**
 * Auto Generated By Hap Code Generator
 *
 * @author xiaoli.yu
 * @version 0.1
 * @name:
 * @Description: 添加员工管理界面的导入对象-美克员工dto
 * @date 2017/7/10 14:37
 */

import com.hand.common.util.ExcelVOAttribute;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "HR_EMPLOYEE")
public class MarkorEmployee extends BaseDTO {
    @Id
    @GeneratedValue(generator = GENERATOR_TYPE)
    private Long employeeId;

    @ExcelVOAttribute(name = "员工编码", column = "A", isExport = true)
    private String employeeCode;

    @ExcelVOAttribute(name = "员工姓名", column = "B", isExport = true)
    private String name;

    @ExcelVOAttribute(name = "出生日期", column = "C", isExport = true)
    private Date bornDate;

    @ExcelVOAttribute(name = "邮件", column = "D", isExport = true)
    private String email;

    @ExcelVOAttribute(name = "移动电话", column = "E", isExport = true)
    private String mobil;

    @ExcelVOAttribute(name = "入职日期", column = "F", isExport = true)
    private Date joinDate;

    @ExcelVOAttribute(name = "性别", column = "G", isExport = true)
    private String gender;

    @ExcelVOAttribute(name = "证件类型", column = "H", isExport = true)
    private String certificateType;

    @ExcelVOAttribute(name = "证件号", ColumnWidth = "5000", column = "I", isExport = true)
    private String certificateId;

    @ExcelVOAttribute(name = "状态", column = "J", isExport = true)
    private String status;

    @ExcelVOAttribute(name = "启用状态", column = "K", isExport = true)
    private String enabledFlag;

    @ExcelVOAttribute(name = "有效日期从", column = "L", isExport = true)
    private Date effectiveStartDate;

    @ExcelVOAttribute(name = "有效日期至", column = "M", isExport = true)
    private Date effectiveEndDate;

    public String getCertificateType() {
        return certificateType;
    }

    public void setCertificateType(String certificateType) {
        this.certificateType = certificateType;
    }

    public Date getEffectiveStartDate() {
        return effectiveStartDate;
    }

    public void setEffectiveStartDate(Date effectiveStartDate) {
        this.effectiveStartDate = effectiveStartDate;
    }

    public Date getEffectiveEndDate() {
        return effectiveEndDate;
    }

    public void setEffectiveEndDate(Date effectiveEndDate) {
        this.effectiveEndDate = effectiveEndDate;
    }

    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    public Long getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode;
    }

    public String getEmployeeCode() {
        return employeeCode;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setBornDate(Date bornDate) {
        this.bornDate = bornDate;
    }

    public Date getBornDate() {
        return bornDate;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmail() {
        return email;
    }

    public void setMobil(String mobil) {
        this.mobil = mobil;
    }

    public String getMobil() {
        return mobil;
    }

    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    public Date getJoinDate() {
        return joinDate;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getGender() {
        return gender;
    }

    public void setCertificateId(String certificateId) {
        this.certificateId = certificateId;
    }

    public String getCertificateId() {
        return certificateId;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStatus() {
        return status;
    }

    public void setEnabledFlag(String enabledFlag) {
        this.enabledFlag = enabledFlag;
    }

    public String getEnabledFlag() {
        return enabledFlag;
    }

}
