package com.hand.hmall.om.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "HMALL_OM_ACCOUNTS")
public class OmAccounts extends BaseDTO {
    /**
     * id
     */
    @Id
    @GeneratedValue(generator = GENERATOR_TYPE)
    @Column
    private Long accountsId;

    /**
     * 第三方交易号
     */
    @Column
    private String transaction;

    /**
     * 财务流水号支付宝有，微信没有，银联暂时没定
     */
    @Column
    private String serialNum;

    /**
     * 商户订单号
     */
    @Column
    private String outTradeNo;

    /**
     * 产品名称
     */
    @Column
    private String product;

    /**
     * 交易时间
     */
    @Column
    private Date time;

    /**
     * 交易账户
     */
    @Column
    private String account;

    /**
     * 交易金额
     */
    @Column
    private BigDecimal amount;

    /**
     * 支付mode WECHAT/ALIPAY/UNIONPAY
     */
    @Column
    private String channel;

    /**
     * 账单类型 1-支付 2-退款 3-支付手续费 4-退款手续费 5-提现
     */
    @Column
    private String type;

    /**
     * 支付宝存备注，微信存产品名称
     */
    @Column
    private String remark;

    //同步retail标记
    @Column
    private String syncFlag;

    //会计凭证编号
    @Column
    private String voucherno;

    //原始业务类型
    @Column
    private String preType;

    //来源标识
    @Column
    private String source;

    //商城订单号
    @Transient
    private String escOrderCode;

    //用户代码
    @Transient
    private String userNumber;

    //公司代码
    @Transient
    private String companyCode;

    //交易日期
    @Transient
    private String tradeDate;

    //交易日期
    @Transient
    private String startTradeDate;

    //交易日期
    @Transient
    private String endTradeDate;

    //交易时间
    @Transient
    private String tradeTime;

    public String getVoucherno() {
        return voucherno;
    }

    public void setVoucherno(String voucherno) {
        this.voucherno = voucherno;
    }

    public String getPreType() {
        return preType;
    }

    public void setPreType(String preType) {
        this.preType = preType;
    }

    public String getSyncFlag() {
        return syncFlag;
    }

    public void setSyncFlag(String syncFlag) {
        this.syncFlag = syncFlag;
    }

    public Long getAccountsId() {
        return accountsId;
    }

    public void setAccountsId(Long accountsId) {
        this.accountsId = accountsId;
    }

    public String getTransaction() {
        return transaction;
    }

    public void setTransaction(String transaction) {
        this.transaction = transaction;
    }

    public String getSerialNum() {
        return serialNum;
    }

    public void setSerialNum(String serialNum) {
        this.serialNum = serialNum;
    }

    public String getOutTradeNo() {
        return outTradeNo;
    }

    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo;
    }

    public String getProduct() {
        return product;
    }

    public void setProduct(String product) {
        this.product = product;
    }

    public Date getTime() {
        return time;
    }

    public void setTime(Date time) {
        this.time = time;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getChannel() {
        return channel;
    }

    public void setChannel(String channel) {
        this.channel = channel;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getEscOrderCode() {
        return escOrderCode;
    }

    public void setEscOrderCode(String escOrderCode) {
        this.escOrderCode = escOrderCode;
    }

    public String getUserNumber() {
        return userNumber;
    }

    public void setUserNumber(String userNumber) {
        this.userNumber = userNumber;
    }

    public String getCompanyCode() {
        return companyCode;
    }

    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    public String getStartTradeDate() {
        return startTradeDate;
    }

    public void setStartTradeDate(String startTradeDate) {
        this.startTradeDate = startTradeDate;
    }

    public String getEndTradeDate() {
        return endTradeDate;
    }

    public void setEndTradeDate(String endTradeDate) {
        this.endTradeDate = endTradeDate;
    }

    public String getTradeDate() {
        return tradeDate;
    }

    public void setTradeDate(String tradeDate) {
        this.tradeDate = tradeDate;
    }

    public String getTradeTime() {
        return tradeTime;
    }

    public void setTradeTime(String tradeTime) {
        this.tradeTime = tradeTime;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }
}
