package com.hand.hmall.om.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "HMALL_OM_DISCOUNT_NOTICE")
public class OmDiscountNotice extends BaseDTO {

    @Id
    @GeneratedValue
    private Long noticeId;

    private Long discountId;

    private String platfromCode;

    private String vcode;

    private Date noticeTime;


    public Long getNoticeId() {
        return noticeId;
    }

    public void setNoticeId(Long noticeId) {
        this.noticeId = noticeId;
    }

    public Long getDiscountId() {
        return discountId;
    }

    public void setDiscountId(Long discountId) {
        this.discountId = discountId;
    }

    public void setPlatfromCode(String platfromCode) {
        this.platfromCode = platfromCode;
    }

    public String getPlatfromCode() {
        return platfromCode;
    }

    public void setVcode(String vcode) {
        this.vcode = vcode;
    }

    public String getVcode() {
        return vcode;
    }

    public void setNoticeTime(Date noticeTime) {
        this.noticeTime = noticeTime;
    }

    public Date getNoticeTime() {
        return noticeTime;
    }

}
