package com.hand.hmall.om.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "HMALL_OM_MAILTEMPLATE")
public class OmMailtemplate extends BaseDTO {
     @Id
     @GeneratedValue(generator = GENERATOR_TYPE)
     @Column
      private Long id;

     @Column
      private String code;

     @Column
      private String templateName;

     @Column
      private String sendtype;

     @Column
      private String msgTemplate;

     @Column
      private Date creationDate;

     @Column
      private Long createdBy;

     @Column
      private Long lastUpdatedBy;

     @Column
      private Date lastUpdateDate;

     @Column
      private Long lastUpdateLogin;

     @Column
      private Long programApplicationId;

     @Column
      private Long programId;

     @Column
      private Date programUpdateDate;

     @Column
      private Long requestId;

     @Column
      private String attributeCategory;

     @Column
      private String attribute1;

     @Column
      private String attribute2;

     @Column
      private String attribute3;

     @Column
      private String attribute4;

     @Column
      private String attribute5;

     @Column
      private String attribute6;

     @Column
      private String attribute7;

     @Column
      private String attribute8;

     @Column
      private String attribute9;

     @Column
      private String attribute10;

     @Column
      private String attribute11;

     @Column
      private String attribute12;

     @Column
      private String attribute13;

     @Column
      private String attribute14;

     @Column
      private String attribute15;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setCode(String code){
         this.code = code;
     }

     public String getCode(){
         return code;
     }

     public void setTemplateName(String templateName){
         this.templateName = templateName;
     }

     public String getTemplateName(){
         return templateName;
     }

     public void setSendtype(String sendtype){
         this.sendtype = sendtype;
     }

     public String getSendtype(){
         return sendtype;
     }

     public void setMsgTemplate(String msgTemplate){
         this.msgTemplate = msgTemplate;
     }

     public String getMsgTemplate(){
         return msgTemplate;
     }

     public void setCreationDate(Date creationDate){
         this.creationDate = creationDate;
     }

     public Date getCreationDate(){
         return creationDate;
     }

     public void setCreatedBy(Long createdBy){
         this.createdBy = createdBy;
     }

     public Long getCreatedBy(){
         return createdBy;
     }

     public void setLastUpdatedBy(Long lastUpdatedBy){
         this.lastUpdatedBy = lastUpdatedBy;
     }

     public Long getLastUpdatedBy(){
         return lastUpdatedBy;
     }

     public void setLastUpdateDate(Date lastUpdateDate){
         this.lastUpdateDate = lastUpdateDate;
     }

     public Date getLastUpdateDate(){
         return lastUpdateDate;
     }

     public void setLastUpdateLogin(Long lastUpdateLogin){
         this.lastUpdateLogin = lastUpdateLogin;
     }

     public Long getLastUpdateLogin(){
         return lastUpdateLogin;
     }

     public void setProgramApplicationId(Long programApplicationId){
         this.programApplicationId = programApplicationId;
     }

     public Long getProgramApplicationId(){
         return programApplicationId;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setProgramUpdateDate(Date programUpdateDate){
         this.programUpdateDate = programUpdateDate;
     }

     public Date getProgramUpdateDate(){
         return programUpdateDate;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     public void setAttributeCategory(String attributeCategory){
         this.attributeCategory = attributeCategory;
     }

     public String getAttributeCategory(){
         return attributeCategory;
     }

     public void setAttribute1(String attribute1){
         this.attribute1 = attribute1;
     }

     public String getAttribute1(){
         return attribute1;
     }

     public void setAttribute2(String attribute2){
         this.attribute2 = attribute2;
     }

     public String getAttribute2(){
         return attribute2;
     }

     public void setAttribute3(String attribute3){
         this.attribute3 = attribute3;
     }

     public String getAttribute3(){
         return attribute3;
     }

     public void setAttribute4(String attribute4){
         this.attribute4 = attribute4;
     }

     public String getAttribute4(){
         return attribute4;
     }

     public void setAttribute5(String attribute5){
         this.attribute5 = attribute5;
     }

     public String getAttribute5(){
         return attribute5;
     }

     public void setAttribute6(String attribute6){
         this.attribute6 = attribute6;
     }

     public String getAttribute6(){
         return attribute6;
     }

     public void setAttribute7(String attribute7){
         this.attribute7 = attribute7;
     }

     public String getAttribute7(){
         return attribute7;
     }

     public void setAttribute8(String attribute8){
         this.attribute8 = attribute8;
     }

     public String getAttribute8(){
         return attribute8;
     }

     public void setAttribute9(String attribute9){
         this.attribute9 = attribute9;
     }

     public String getAttribute9(){
         return attribute9;
     }

     public void setAttribute10(String attribute10){
         this.attribute10 = attribute10;
     }

     public String getAttribute10(){
         return attribute10;
     }

     public void setAttribute11(String attribute11){
         this.attribute11 = attribute11;
     }

     public String getAttribute11(){
         return attribute11;
     }

     public void setAttribute12(String attribute12){
         this.attribute12 = attribute12;
     }

     public String getAttribute12(){
         return attribute12;
     }

     public void setAttribute13(String attribute13){
         this.attribute13 = attribute13;
     }

     public String getAttribute13(){
         return attribute13;
     }

     public void setAttribute14(String attribute14){
         this.attribute14 = attribute14;
     }

     public String getAttribute14(){
         return attribute14;
     }

     public void setAttribute15(String attribute15){
         this.attribute15 = attribute15;
     }

     public String getAttribute15(){
         return attribute15;
     }

     }
