package com.hand.hmall.om.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "HMALL_OM_PROMOTIONRULE")
public class OmPromotionrule extends BaseDTO {
    @Id
    @GeneratedValue(generator = GENERATOR_TYPE)
    @Column
    private Long promotionruleId;

    @Column
    private Long orderId;

    @Column
    private String activityId;

    @Column
    private String activityName;

    @Column
    private String releaseId;

    @Column
    private String type;

    @Column
    private String activityDes;

    @Transient
    private String pageShowMes;
    @Column
    private String pageShowmes;
    @Column
    private Long amount;
    /**
     * 数据库字段名为startTime 但是接口返回字段为startDate
     */
    @Transient
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm;ss")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private String startDate;
    @Transient
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm;ss")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private String endDate;

    @Column
    private Date startTime;

    @Column
    private Date endTime;

    @Column
    private Long giftQuantity;

    public String getPageShowmes() {
        return pageShowmes;
    }

    public void setPageShowmes(String pageShowmes) {
        this.pageShowmes = pageShowmes;
    }

    public String getPageShowMes() {
        return pageShowMes;
    }

    public void setPageShowMes(String pageShowMes) {
        this.pageShowMes = pageShowMes;
    }

    public Long getAmount() {
        return amount;
    }

    public void setAmount(Long amount) {
        this.amount = amount;
    }

    public String getStartDate() {
        return startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    public String getEndDate() {
        return endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    public Long getGiftQuantity() {
        return giftQuantity;
    }

    public void setGiftQuantity(Long giftQuantity) {
        this.giftQuantity = giftQuantity;
    }

    public void setPromotionruleId(Long promotionruleId) {
        this.promotionruleId = promotionruleId;
    }

    public Long getPromotionruleId() {
        return promotionruleId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public Long getOrderId() {
        return orderId;
    }

    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    public String getActivityId() {
        return activityId;
    }

    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }

    public String getActivityName() {
        return activityName;
    }

    public void setReleaseId(String releaseId) {
        this.releaseId = releaseId;
    }

    public String getReleaseId() {
        return releaseId;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getType() {
        return type;
    }

    public void setActivityDes(String activityDes) {
        this.activityDes = activityDes;
    }

    public String getActivityDes() {
        return activityDes;
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}
