package com.hand.hmall.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.*;

@Table(name = "HMALL_MST_SUBCATEGORY")
public class MstSubcategory {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY, generator = "select HMALL_MST_SUBCATEGORY_S.nextval from dual")
     @Column
      private Long mappingId;

     @Column
      private Long categoryId;

     @Column
      private Long subCategoryId;

     @Column
      private String syncflag;


     public void setMappingId(Long mappingId){
         this.mappingId = mappingId;
     }

     public Long getMappingId(){
         return mappingId;
     }

     public void setCategoryId(Long categoryId){
         this.categoryId = categoryId;
     }

     public Long getCategoryId(){
         return categoryId;
     }

     public void setSubCategoryId(Long subCategoryId){
         this.subCategoryId = subCategoryId;
     }

     public Long getSubCategoryId(){
         return subCategoryId;
     }

     public void setSyncflag(String syncflag){
         this.syncflag = syncflag;
     }

     public String getSyncflag(){
         return syncflag;
     }

     }
