package com.hand.hmall.model;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.*;
import java.util.Date;

/**
 * @author zhangmeng
 * @version 0.1
 * @name DiscountEntry
 * @description 价格折扣行
 * @date 2017/11/27
 */
@Entity
@Table(name = "HMALL_OM_DISCOUNT_ENTRY")
public class DiscountEntry {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY, generator = "select HMALL_OM_DISCOUNT_ENTRY_S.nextval from dual")
    private Long discountId;

    private Long productId;

    private Long catalogversionId;

    private Double discount;

    private Long discountType;

    private Date startTime;

    private Date endTime;

    private String isHandle;

    private String vcode;
    //折扣后价格
    @Transient
    private Double discountPrice;
    @Transient
    private String startTimeStr;
    @Transient
    private String endTimeStr;
    @Transient
    private String type;

    public String getVcode() {
        return vcode;
    }

    public void setVcode(String vcode) {
        this.vcode = vcode;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getStartTimeStr() {
        return startTimeStr;
    }

    public void setStartTimeStr(String startTimeStr) {
        this.startTimeStr = startTimeStr;
    }

    public String getEndTimeStr() {
        return endTimeStr;
    }

    public void setEndTimeStr(String endTimeStr) {
        this.endTimeStr = endTimeStr;
    }

    public String getIsHandle() {
        return isHandle;
    }

    public void setIsHandle(String isHandle) {
        this.isHandle = isHandle;
    }

    public Double getDiscountPrice() {
        return discountPrice;
    }

    public void setDiscountPrice(Double discountPrice) {
        this.discountPrice = discountPrice;
    }

    public void setDiscountId(Long discountId) {
        this.discountId = discountId;
    }

    public Long getDiscountId() {
        return discountId;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public void setCatalogversionId(Long catalogversionId) {
        this.catalogversionId = catalogversionId;
    }

    public Long getCatalogversionId() {
        return catalogversionId;
    }

    public Double getDiscount() {
        return discount;
    }

    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    public void setDiscountType(Long discountType) {
        this.discountType = discountType;
    }

    public Long getDiscountType() {
        return discountType;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public Date getEndTime() {
        return endTime;
    }

}
