package com.hand.hmall.mst.dto;

/**
 * Auto Generated By Hap Code Generator
 *
 * @author xiaoli.yu
 * @version 0.1
 * @name:
 * @Description: 商铺对象dto
 * @date 2017/7/20 16:05
 */

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable = true)
@Table(name = "HMALL_MST_BASESTORE")
public class Basestore extends BaseDTO {
    @Id
    @GeneratedValue(generator = GENERATOR_TYPE)
    @Column
    private Long basestoreId;

    @Column
    private String code;

    @Column
    private String displayName;

    @Column
    private String syncflag;

    @Column
    private Double inventoryRatio;

    @Column
    private Long stockTheshold;

    @Column
    private Long relatedCatalog;

    public Double getInventoryRatio() {
        return inventoryRatio;
    }

    public void setInventoryRatio(Double inventoryRatio) {
        this.inventoryRatio = inventoryRatio;
    }

    public Long getStockTheshold() {
        return stockTheshold;
    }

    public void setStockTheshold(Long stockTheshold) {
        this.stockTheshold = stockTheshold;
    }

    public Long getRelatedCatalog() {
        return relatedCatalog;
    }

    public void setRelatedCatalog(Long relatedCatalog) {
        this.relatedCatalog = relatedCatalog;
    }

    public void setBasestoreId(Long basestoreId) {
        this.basestoreId = basestoreId;
    }

    public Long getBasestoreId() {
        return basestoreId;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setSyncflag(String syncflag) {
        this.syncflag = syncflag;
    }

    public String getSyncflag() {
        return syncflag;
    }

}
