package com.hand.hmall.mst.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.*;

/**
 * @author peng.chen03@hand-china.com
 * @version 0.1
 * @name Catalogversion
 * @description 目录版本dto
 * @date 2017年5月26日10:52:23
 */
@ExtensionAttribute(disable = true)
@Table(name = "HMALL_MST_CATALOGVERSION")
public class Catalogversion extends BaseDTO {
    @Id
    @GeneratedValue(generator = GENERATOR_TYPE)
    @Column
    private Long catalogversionId;

    @Column
    private Long catalog;

    @Column
    private String catalogversion;

    //组合版本名称
    @Transient
    private String catalogName;

    //版本编码Code
    @Transient
    private String code;

    //目录版本中文
    @Transient
    private String catalogNameZh;

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getCatalogName() {
        return catalogName;
    }

    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName;
    }

    public Long getCatalogversionId() {
        return catalogversionId;
    }

    public void setCatalogversionId(Long catalogversionId) {
        this.catalogversionId = catalogversionId;
    }

    public Long getCatalog() {
        return catalog;
    }

    public void setCatalog(Long catalog) {
        this.catalog = catalog;
    }

    public String getCatalogversion() {
        return catalogversion;
    }

    public void setCatalogversion(String catalogversion) {
        this.catalogversion = catalogversion;
    }

    public String getCatalogNameZh() {
        return catalogNameZh;
    }

    public void setCatalogNameZh(String catalogNameZh) {
        this.catalogNameZh = catalogNameZh;
    }
}
