package com.hand.hmall.mst.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.common.util.ExcelVOAttribute;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.*;
import java.math.BigDecimal;

/**
 * @author xiaoli.yu
 * @version 0.1
 * @name:
 * @Description: 安装费对象dto
 * @date 2017/7/10 14:37
 */
@ExtensionAttribute(disable = true)
@Table(name = "HMALL_MST_INSTALLATION")
public class Installation extends BaseDTO {
    @Id
    @GeneratedValue(generator = GENERATOR_TYPE)
    @Column
    private Long installationId;

    @Column
    private Long categoryId;

    @Column
    @ExcelVOAttribute(name = "安装费", column = "B", isExport = true)
    private BigDecimal installationFee;

    @Column
    @ExcelVOAttribute(name = "是否启用(Y/N)", column = "C", isExport = true)
    private String status;

    @Transient
    @ExcelVOAttribute(name = "类别编码", column = "A", isExport = true)
    private String categoryCode;//类别编码

    @Transient
    private String categoryName;//类别名称

    public String getCategoryCode() {
        return categoryCode;
    }

    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public void setInstallationId(Long installationId) {
        this.installationId = installationId;
    }

    public Long getInstallationId() {
        return installationId;
    }

    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    public Long getCategoryId() {
        return categoryId;
    }

    public BigDecimal getInstallationFee() {
        return installationFee;
    }

    public void setInstallationFee(BigDecimal installationFee) {
        this.installationFee = installationFee;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStatus() {
        return status;
    }

}
