package com.hand.hmall.mst.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Column;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "HMALL_MST_BASESTORE")
public class MstBasestore extends BaseDTO {
     @Id
     @GeneratedValue(generator = GENERATOR_TYPE)
     @Column
      private Long basestoreId;

     @Column
      private String code;

     @Column
      private String displayName;

     @Column
      private String syncflag;


     public void setBasestoreId(Long basestoreId){
         this.basestoreId = basestoreId;
     }

     public Long getBasestoreId(){
         return basestoreId;
     }

     public void setCode(String code){
         this.code = code;
     }

     public String getCode(){
         return code;
     }

     public void setDisplayName(String displayName){
         this.displayName = displayName;
     }

     public String getDisplayName(){
         return displayName;
     }

     public void setSyncflag(String syncflag){
         this.syncflag = syncflag;
     }

     public String getSyncflag(){
         return syncflag;
     }

     }
