package com.hand.hmall.mst.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.common.util.ExcelVOAttribute;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * @author peng.chen
 * @version 0.1
 * @name:
 * @Description: 面料等级对象dto
 * @date 2017/7/10 14:37
 */
@ExtensionAttribute(disable = true)
@Table(name = "HMALL_MST_FABRIC")
public class MstFabric extends BaseDTO {
    @Id
    @GeneratedValue(generator = GENERATOR_TYPE)
    @Column
    private Long fabricId;

    @Column
    @ExcelVOAttribute(name = "面料编码", column = "A")
    private String fabricCode;

    @Column
    @ExcelVOAttribute(name = "面料等级", column = "B")
    private String fabricLevel;

    @Column
    private String syncflag;


    public void setFabricId(Long fabricId) {
        this.fabricId = fabricId;
    }

    public Long getFabricId() {
        return fabricId;
    }

    public void setFabricCode(String fabricCode) {
        this.fabricCode = fabricCode;
    }

    public String getFabricCode() {
        return fabricCode;
    }

    public void setFabricLevel(String fabricLevel) {
        this.fabricLevel = fabricLevel;
    }

    public String getFabricLevel() {
        return fabricLevel;
    }

    public String getSyncflag() {
        return syncflag;
    }

    public void setSyncflag(String syncflag) {
        this.syncflag = syncflag;
    }
}
