package com.hand.hmall.mst.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Column;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

/**
 * @author xiaoyu.ran
 * @version 0.1
 * @name:
 * @Description: 商品单位维护对象dto
 * @date 2017/9/5 14:54
 */
@ExtensionAttribute(disable=true)
@Table(name = "HMALL_MST_UNIT")
public class MstUnit extends BaseDTO {
     @Id
     @GeneratedValue(generator = GENERATOR_TYPE)
     @Column
      private Long unitId;

     @Column
      private String code;

     @Column
      private String description;

     @Column
      private String type;

     @Column
      private String baseUnit;

     @Column
      private Long rate;

     @Column
      private String active;


     public void setUnitId(Long unitId){
         this.unitId = unitId;
     }

     public Long getUnitId(){
         return unitId;
     }

     public void setCode(String code){
         this.code = code;
     }

     public String getCode(){
         return code;
     }

     public void setDescription(String description){
         this.description = description;
     }

     public String getDescription(){
         return description;
     }

     public void setType(String type){
         this.type = type;
     }

     public String getType(){
         return type;
     }

     public void setBaseUnit(String baseUnit){
         this.baseUnit = baseUnit;
     }

     public String getBaseUnit(){
         return baseUnit;
     }

     public void setRate(Long rate){
         this.rate = rate;
     }

     public Long getRate(){
         return rate;
     }

     public void setActive(String active){
         this.active = active;
     }

     public String getActive(){
         return active;
     }

     }
