package com.hand.hmall.mst.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Column;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

/**
 * @author xiaoli.yu
 * @version 0.1
 * @name:
 * @Description: 频道对象dto
 * @date 2017/8/11 17:33
 */
@ExtensionAttribute(disable=true)
@Table(name = "HMALL_MST_ODTYPE")
public class Odtype extends BaseDTO {
     @Id
     @GeneratedValue(generator = GENERATOR_TYPE)
     @Column
      private Long odtypeId;

     @Column
      private Long productId;

     @Column
      private String custChanSrc;

     @Column
      private String approvalStatus;

     @Column
      private String isUsed;


     public void setOdtypeId(Long odtypeId){
         this.odtypeId = odtypeId;
     }

     public Long getOdtypeId(){
         return odtypeId;
     }

     public void setProductId(Long productId){
         this.productId = productId;
     }

     public Long getProductId(){
         return productId;
     }

     public void setCustChanSrc(String custChanSrc){
         this.custChanSrc = custChanSrc;
     }

     public String getCustChanSrc(){
         return custChanSrc;
     }

     public void setApprovalStatus(String approvalStatus){
         this.approvalStatus = approvalStatus;
     }

     public String getApprovalStatus(){
         return approvalStatus;
     }

     public void setIsUsed(String isUsed){
         this.isUsed = isUsed;
     }

     public String getIsUsed(){
         return isUsed;
     }

     }
