package com.hand.hmall.mst.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

/**
 * @author xiaoli.yu
 * @version 0.1
 * @name:
 * @Description: 推送至商城的频道对象dto
 * @date 2017/8/11 17:33
 */
public class OdtypeDto {
    private Long odtypeId;

    private String code;

    private String custChanSrc;

    private String approvalStatus;

    public Long getOdtypeId() {
        return odtypeId;
    }

    public void setOdtypeId(Long odtypeId) {
        this.odtypeId = odtypeId;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public void setCustChanSrc(String custChanSrc) {
        this.custChanSrc = custChanSrc;
    }

    public String getCustChanSrc() {
        return custChanSrc;
    }

    public void setApprovalStatus(String approvalStatus) {
        this.approvalStatus = approvalStatus;
    }

    public String getApprovalStatus() {
        return approvalStatus;
    }


}
