package com.hand.hmall.mst.dto;

import com.hand.common.util.ExcelVOAttribute;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Auto Generated By Hap Code Generator
 **/

/**
 * @author xiaoli.yu
 * @version 0.1
 * @name:
 * @Description: 价格行对象dto
 * @date 2017/7/10 14:37
 */
@ExtensionAttribute(disable = true)
@Table(name = "HMALL_MST_PRICEROW")
public class Pricerow extends BaseDTO {
    /**
     *
     */
    private static final long serialVersionUID = -7898085602838315093L;

    @Id
    @GeneratedValue
    private Long pricerowId;

    private Long productId;

    private Long userId;

    private Long userGroupId;

    @ExcelVOAttribute(name = "价格", column = "G", isExport = true)
    private BigDecimal basePrice;

    private BigDecimal bottomPrice;

    @ExcelVOAttribute(name = "销售单位", column = "H", isExport = true)
    private String saleUnit;

    private BigDecimal rate;

    @ExcelVOAttribute(name = "开始时间", column = "I", isExport = true)
    private Date startTime;

    @ExcelVOAttribute(name = "结束时间", column = "J", isExport = true)
    private Date endTime;

    @ExcelVOAttribute(name = "价格类型", column = "C", isExport = true)
    private String priceType;

    @ExcelVOAttribute(name = "框架等级", column = "D", isExport = true)
    private String productGrade;

    private String isBottom;

    private String syncflag;

    @ExcelVOAttribute(name = "价目表", column = "E", isExport = true)
    private String priceGroup;

    @Transient
    private Date creationsDate;

    @Transient
    @ExcelVOAttribute(name = "商品编号", column = "A", isExport = true)
    private String code;//商品编码

    @Transient
    private String name;//用户组名

    @Transient
    private String userName;//用户名

    @Transient
    private String productName; //商品名称

    @Transient
    @ExcelVOAttribute(name = "用户", column = "F", isExport = true)
    private String customerid;//用户账号

    @Transient
    private String productType;//商品类型

    @Transient
    private Long syncProductId;//同步后的productId

    @Transient
    @ExcelVOAttribute(name = "目录版本", column = "B", isExport = true)
    private String catalogName;//目录版本名称

    private Long catalogversionId; //目录版本Id

    @ExcelVOAttribute(name = "频道", column = "L", isExport = true)
    private String odtype;

    @Transient
    @ExcelVOAttribute(name = "是否覆盖原纪录(Y/N)", ColumnWidth = "5000", column = "K", isExport = true)
    private String isCovered; //导入模板中是否覆盖原纪录



    public Long getCatalogversionId() {
        return catalogversionId;
    }

    public void setCatalogversionId(Long catalogversionId) {
        this.catalogversionId = catalogversionId;
    }

    public String getCatalogName() {
        return catalogName;
    }

    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName;
    }

    public String getIsCovered() {
        return isCovered;
    }

    public void setIsCovered(String isCovered) {
        this.isCovered = isCovered;
    }

    public Long getSyncProductId() {
        return syncProductId;
    }

    public void setSyncProductId(Long syncProductId) {
        this.syncProductId = syncProductId;
    }

    public String getPriceGroup() {
        return priceGroup;
    }

    public void setPriceGroup(String priceGroup) {
        this.priceGroup = priceGroup;
    }

    public String getProductType() {
        return productType;
    }

    public void setProductType(String productType) {
        this.productType = productType;
    }

    public String getCustomerid() {
        return customerid;
    }

    public void setCustomerid(String customerid) {
        this.customerid = customerid;
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public String getPriceType() {
        return priceType;
    }

    public void setPriceType(String priceType) {
        this.priceType = priceType;
    }

    public String getProductGrade() {
        return productGrade;
    }

    public void setProductGrade(String productGrade) {
        this.productGrade = productGrade;
    }

    public String getIsBottom() {
        return isBottom;
    }

    public void setIsBottom(String isBottom) {
        this.isBottom = isBottom;
    }

    public Long getPricerowId() {
        return pricerowId;
    }

    public void setPricerowId(Long pricerowId) {
        this.pricerowId = pricerowId;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getUserGroupId() {
        return userGroupId;
    }

    public void setUserGroupId(Long userGroupId) {
        this.userGroupId = userGroupId;
    }

    public BigDecimal getBasePrice() {
        return basePrice;
    }

    public void setBasePrice(BigDecimal basePrice) {
        this.basePrice = basePrice;
    }

    public BigDecimal getBottomPrice() {
        return bottomPrice;
    }

    public void setBottomPrice(BigDecimal bottomPrice) {
        this.bottomPrice = bottomPrice;
    }

    public String getSaleUnit() {
        return saleUnit;
    }

    public void setSaleUnit(String saleUnit) {
        this.saleUnit = saleUnit;
    }

    public BigDecimal getRate() {
        return rate;
    }

    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    public String getSyncflag() {
        return syncflag;
    }

    public void setSyncflag(String syncflag) {
        this.syncflag = syncflag;
    }

    public Date getCreationsDate() {
        return creationsDate;
    }

    public void setCreationsDate(Date creationsDate) {
        this.creationsDate = creationsDate;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getOdtype() {
        return odtype;
    }

    public void setOdtype(String odtype) {
        this.odtype = odtype;
    }

    @Override
    public String toString() {
        return "Pricerow{" +
                "pricerowId=" + pricerowId +
                ", productId=" + productId +
                ", userId=" + userId +
                ", userGroupId=" + userGroupId +
                ", basePrice=" + basePrice +
                ", bottomPrice=" + bottomPrice +
                ", saleUnit='" + saleUnit + '\'' +
                ", rate=" + rate +
                ", startTime=" + startTime +
                ", endTime=" + endTime +
                ", priceType='" + priceType + '\'' +
                ", productGrade='" + productGrade + '\'' +
                ", isBottom='" + isBottom + '\'' +
                ", syncflag='" + syncflag + '\'' +
                ", priceGroup='" + priceGroup + '\'' +
                ", creationsDate=" + creationsDate +
                ", code='" + code + '\'' +
                ", name='" + name + '\'' +
                ", userName='" + userName + '\'' +
                ", productName='" + productName + '\'' +
                ", customerid='" + customerid + '\'' +
                ", productType='" + productType + '\'' +
                ", syncProductId=" + syncProductId +
                '}';
    }
}
