package com.hand.hmall.mst.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.common.util.ExcelVOAttribute;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * @author xiaoli.yu
 * @version 0.1
 * @name:
 * @Description: 商品对象dto
 * @date 2017/7/10 14:37
 */
@ExtensionAttribute(disable = true)
@Table(name = "HMALL_MST_PRODUCT")
public class Product extends BaseDTO {
    /**
     *
     */
    private static final long serialVersionUID = -4545740182783539853L;

    @Id
    @GeneratedValue
    private Long productId;

    @ExcelVOAttribute(name = "商品编码", column = "A", isExport = true)
    private String code;

    private String name;

    private Long catalogversionId;

    private String approvalStatus;

    private String unit;

    private Long imageUrlId;


    /**
     * 图片URL
     */
    @Transient
    private String imageUrl;
    /**
     * 服务单code
     */
    @Transient
    private Long serviceOrderId;
    @Transient
    private List<String> excludeProductIds;

    private Long thumbnilUrlId;

    private Long baseProductId;

    private Long variantProductId;

    private String productType;

    private String customType;

    private String isSuit;

    private String isSinSale;

    private String saleStatus;

    private Long brandId;

    private String productStatus;

    private Date listingTime;

    private Date delistingTime;

    private String isSpeSale;

    private String originCountry;

    private String sourcePlace;

    private BigDecimal miniOrderQuantity;

    private BigDecimal rate;

    private String stype;

    private String designType;

    private BigDecimal pLong;

    private BigDecimal pWide;

    private BigDecimal pHigh;

    private String sizeSpecification;

    private String sizeUnit;

    private BigDecimal packingLong;

    private BigDecimal packingWide;

    private BigDecimal packingHigh;

    private String packingUnit;

    private BigDecimal packingVolume;

    private String packingVolUnit;

    private BigDecimal grossWeight;

    private BigDecimal netWeight;

    private String weightUnit;

    private String shape;

    private String texture;

    private String textureSpecification;

    private String maintainSpecification;

    private String isResin;

    private BigDecimal netCapacity;

    private String netCapacityUnit;

    private String qgp;

    private String syncflag;

    private Date creationDate;

    private Long objectVersionNumber;

    private Long createdBy;

    private Long lastUpdatedBy;

    /**
     * 创建日期开始
     */
    @Transient
    private String creationDateFrom;
    /**
     * 创建日期结束
     */
    @Transient
    private String creationDateTo;

    @Transient
    private String status;//更新还是插入

    @Transient
    private Long versionProductId;//查询目录版本下的商品ID

    @Transient
    @ExcelVOAttribute(name = "目录版本", column = "B", isExport = true)
    private String versionCode;//目录版本code

    @Transient
    private Date syncData;//上次同步时间

    @Transient
    private Long catalog;

    @Transient
    private Long basePrice;

    private Long lastUpdateLogin;

    private Date lastUpdateDate;
    /**
     * 目录版本
     */
    @Transient
    private String catalogversion;

    private String nameEn;

    @ExcelVOAttribute(name = "商品v码", column = "AT", isExport = true)
    private String vProductCode;

    private String platformCode;

    private String mtart;

    private String matkl;

    @ExcelVOAttribute(name = "积分商品", column = "C", isExport = true)
    private String rewardProduct;

    @ExcelVOAttribute(name = "配送方式", column = "E", isExport = true)
    private String defaultDelivery;

    private String isPreSale;

    @ExcelVOAttribute(name = "主颜色", column = "D", isExport = true)
    private String mainColor;

    @ExcelVOAttribute(name = "是否需要组装", column = "F", isExport = true)
    private String isPackaging;

    @ExcelVOAttribute(name = "特殊功能1", column = "G", isExport = true)
    private String addFunction1;

    @ExcelVOAttribute(name = "特殊功能2", column = "H", isExport = true)
    private String addFunction2;

    @ExcelVOAttribute(name = "特殊功能3", column = "I", isExport = true)
    private String addFunction3;

    @ExcelVOAttribute(name = "是否带储物空间", column = "J", isExport = true)
    private String isStorage;

    @ExcelVOAttribute(name = "沙发组合形式", column = "K", isExport = true)
    private String sofaCombiningForm;

    @ExcelVOAttribute(name = "是否可拆洗", column = "L", isExport = true)
    private String isWashable;

    @ExcelVOAttribute(name = "填充物1", column = "M", isExport = true)
    private String filler1;

    @ExcelVOAttribute(name = "填充物2", column = "N", isExport = true)
    private String filler2;

    @ExcelVOAttribute(name = "填充物3", column = "O", isExport = true)
    private String filler3;

    @ExcelVOAttribute(name = "适用对象", column = "P", isExport = true)
    private String suitableUsers;

    @ExcelVOAttribute(name = "木质工艺1", column = "Q", isExport = true)
    private String woodenCrafts1;

    @ExcelVOAttribute(name = "木质工艺2", column = "R", isExport = true)
    private String woodenCrafts2;

    @ExcelVOAttribute(name = "木质工艺3", column = "S", isExport = true)
    private String woodenCrafts3;

    @ExcelVOAttribute(name = "设计元素1", column = "T", isExport = true)
    private String designElement1;

    @ExcelVOAttribute(name = "设计元素2", column = "U", isExport = true)
    private String designElement2;

    @ExcelVOAttribute(name = "设计元素3", column = "V", isExport = true)
    private String designElement3;

    @ExcelVOAttribute(name = "皮革饰面范围1", column = "W", isExport = true)
    private String leatherRange1;

    private String leatherRange2;

    private String leatherRange3;

    @ExcelVOAttribute(name = "皮革饰面工艺1", column = "X", isExport = true)
    private String leatherCraft1;

    @ExcelVOAttribute(name = "皮革饰面工艺2", column = "Y", isExport = true)
    private String leatherCraft2;

    @ExcelVOAttribute(name = "皮革饰面工艺3", column = "Z", isExport = true)
    private String leatherCraft3;

    @ExcelVOAttribute(name = "是否带软靠", column = "AA", isExport = true)
    private String isSoftCushion;

    @ExcelVOAttribute(name = "是否带滚轮", column = "AB", isExport = true)
    private String isWheel;

    @ExcelVOAttribute(name = "抽屉导轨节数", column = "AC", isExport = true)
    private String drawerRailNum;

    @ExcelVOAttribute(name = "是否带阻尼", column = "AD", isExport = true)
    private String isDamping;

    @ExcelVOAttribute(name = "饰面油漆工艺", column = "AE", isExport = true)
    private String paintCraft;

    @ExcelVOAttribute(name = "抽屉数量", column = "AF", isExport = true)
    private String drawerNumber;

    private String backrestLength;

    private String isRotate;

    @ExcelVOAttribute(name = "特殊工艺价格", column = "AM")
    private String specialPrice;

    @ExcelVOAttribute(name = "特征值", column = "AN")
    private String property;

    @ExcelVOAttribute(name = "是否主商品", column = "AO")
    private String isMain;

    private String filler;

    private String addFunction;

    private String woodenCrafts;

    private String leatherRange;

    private String leatherCraft;

    @ExcelVOAttribute(name = "材质", column = "AG", isExport = true)
    private String material;

    @ExcelVOAttribute(name = "系列名称", column = "AH", isExport = true)
    private String seriesName;

    @ExcelVOAttribute(name = "产品简介", column = "AI", isExport = true)
    private String introduction;

    @ExcelVOAttribute(name = "产品卖点", column = "AJ", isExport = true)
    private String salepoint;

    private String supplier;

    private String style;

    @ExcelVOAttribute(name = "定制支持类型", column = "AK")
    private String customSupportType;

    @ExcelVOAttribute(name = "定制频道来源", column = "AL")
    private String customChannelSource;

    @Transient
    @ExcelVOAttribute(name = "是否有超级定制", column = "AP")
    private String isSuperUsed;     //商品导入时，对应是否有超级定制字段

    @Transient
    @ExcelVOAttribute(name = "是否有普通定制", column = "AQ")
    private String isNormalUsed;  //商品导入时，对应是否有普通定制字段

    @Transient
    @ExcelVOAttribute(name = "超类别", column = "AR")
    private String categoryList; //商品对应的多个超类别，用于商品导入更新excel

    @ExcelVOAttribute(name = "仓库", column = "AS")
    private String warehouse;

    @ExcelVOAttribute(name = "电商商品名称", column = "AU")
    private String escName;

    @Transient
    private String normalApproveStatus;  //普通定制上架状态

    @Transient
    private String superApproveStatus;//超级定制上架状态

    private String fetchImageFlag; // 商品是否已经抓取图片

    public String getEscName() {
        return escName;
    }

    /**
     * 是否可定制
     * 1  可定制
     * 0  不可定制
     */
    @ExcelVOAttribute(name = "是否定制", column = "AV")
    private String hascustom;

    public void setEscName(String escName) {
        this.escName = escName;
    }

    public String getWarehouse() {
        return warehouse;
    }

    public void setWarehouse(String warehouse) {
        this.warehouse = warehouse;
    }

    public String getIsSuperUsed() {
        return isSuperUsed;
    }

    public void setIsSuperUsed(String isSuperUsed) {
        this.isSuperUsed = isSuperUsed;
    }

    public String getIsNormalUsed() {
        return isNormalUsed;
    }

    public void setIsNormalUsed(String isNormalUsed) {
        this.isNormalUsed = isNormalUsed;
    }

    public String getNormalApproveStatus() {
        return normalApproveStatus;
    }

    public void setNormalApproveStatus(String normalApproveStatus) {
        this.normalApproveStatus = normalApproveStatus;
    }

    public String getSuperApproveStatus() {
        return superApproveStatus;
    }

    public void setSuperApproveStatus(String superApproveStatus) {
        this.superApproveStatus = superApproveStatus;
    }

    public String getCustomSupportType() {
        return customSupportType;
    }

    public void setCustomSupportType(String customSupportType) {
        this.customSupportType = customSupportType;
    }

    public String getCustomChannelSource() {
        return customChannelSource;
    }

    public void setCustomChannelSource(String customChannelSource) {
        this.customChannelSource = customChannelSource;
    }

    public String getCategoryList() {
        return categoryList;
    }

    public void setCategoryList(String categoryList) {
        this.categoryList = categoryList;
    }

    public String getFiller() {
        return filler;
    }

    public void setFiller(String filler) {
        this.filler = filler;
    }

    public String getAddFunction() {
        return addFunction;
    }

    public void setAddFunction(String addFunction) {
        this.addFunction = addFunction;
    }

    public String getWoodenCrafts() {
        return woodenCrafts;
    }

    public void setWoodenCrafts(String woodenCrafts) {
        this.woodenCrafts = woodenCrafts;
    }

    public String getLeatherRange() {
        return leatherRange;
    }

    public void setLeatherRange(String leatherRange) {
        this.leatherRange = leatherRange;
    }

    public String getLeatherCraft() {
        return leatherCraft;
    }

    public void setLeatherCraft(String leatherCraft) {
        this.leatherCraft = leatherCraft;
    }

    public Long getBasePrice() {
        return basePrice;
    }

    public void setBasePrice(Long basePrice) {
        this.basePrice = basePrice;
    }

    public String getMaterial() {
        return material;
    }

    public void setMaterial(String material) {
        this.material = material;
    }

    public String getSeriesName() {
        return seriesName;
    }

    public void setSeriesName(String seriesName) {
        this.seriesName = seriesName;
    }

    public String getIntroduction() {
        return introduction;
    }

    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    public String getSalepoint() {
        return salepoint;
    }

    public void setSalepoint(String salepoint) {
        this.salepoint = salepoint;
    }

    public String getRewardProduct() {
        return rewardProduct;
    }

    public void setRewardProduct(String rewardProduct) {
        this.rewardProduct = rewardProduct;
    }

    public String getDefaultDelivery() {
        return defaultDelivery;
    }

    public void setDefaultDelivery(String defaultDelivery) {
        this.defaultDelivery = defaultDelivery;
    }

    public String getIsPreSale() {
        return isPreSale;
    }

    public void setIsPreSale(String isPreSale) {
        this.isPreSale = isPreSale;
    }

    public String getMainColor() {
        return mainColor;
    }

    public void setMainColor(String mainColor) {
        this.mainColor = mainColor;
    }

    public String getIsPackaging() {
        return isPackaging;
    }

    public void setIsPackaging(String isPackaging) {
        this.isPackaging = isPackaging;
    }

    public String getIsStorage() {
        return isStorage;
    }

    public void setIsStorage(String isStorage) {
        this.isStorage = isStorage;
    }

    public String getSofaCombiningForm() {
        return sofaCombiningForm;
    }

    public void setSofaCombiningForm(String sofaCombiningForm) {
        this.sofaCombiningForm = sofaCombiningForm;
    }

    public String getIsWashable() {
        return isWashable;
    }

    public void setIsWashable(String isWashable) {
        this.isWashable = isWashable;
    }

    public String getSuitableUsers() {
        return suitableUsers;
    }

    public void setSuitableUsers(String suitableUsers) {
        this.suitableUsers = suitableUsers;
    }

    public String getIsSoftCushion() {
        return isSoftCushion;
    }

    public void setIsSoftCushion(String isSoftCushion) {
        this.isSoftCushion = isSoftCushion;
    }

    public String getIsWheel() {
        return isWheel;
    }

    public void setIsWheel(String isWheel) {
        this.isWheel = isWheel;
    }

    public String getDrawerRailNum() {
        return drawerRailNum;
    }

    public void setDrawerRailNum(String drawerRailNum) {
        this.drawerRailNum = drawerRailNum;
    }

    public String getIsDamping() {
        return isDamping;
    }

    public void setIsDamping(String isDamping) {
        this.isDamping = isDamping;
    }

    public String getPaintCraft() {
        return paintCraft;
    }

    public void setPaintCraft(String paintCraft) {
        this.paintCraft = paintCraft;
    }

    public String getDrawerNumber() {
        return drawerNumber;
    }

    public void setDrawerNumber(String drawerNumber) {
        this.drawerNumber = drawerNumber;
    }

    public String getBackrestLength() {
        return backrestLength;
    }

    public void setBackrestLength(String backrestLength) {
        this.backrestLength = backrestLength;
    }

    public String getIsRotate() {
        return isRotate;
    }

    public void setIsRotate(String isRotate) {
        this.isRotate = isRotate;
    }

    public String getPlatformCode() {
        return platformCode;
    }

    public void setPlatformCode(String platformCode) {
        this.platformCode = platformCode;
    }

    public String getvProductCode() {
        return vProductCode;
    }

    public void setvProductCode(String vProductCode) {
        this.vProductCode = vProductCode;
    }

    public String getNameEn() {
        return nameEn;
    }

    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    public String getVersionCode() {
        return versionCode;
    }

    public void setVersionCode(String versionCode) {
        this.versionCode = versionCode;
    }

    public String getCatalogversion() {
        return catalogversion;
    }

    public void setCatalogversion(String catalogversion) {
        this.catalogversion = catalogversion;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    @Override
    public Date getCreationDate() {
        return creationDate;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @Override
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public String getCreationDateFrom() {
        return creationDateFrom;
    }

    public void setCreationDateFrom(String creationDateFrom) {
        this.creationDateFrom = creationDateFrom;
    }

    public String getCreationDateTo() {
        return creationDateTo;
    }

    public void setCreationDateTo(String creationDateTo) {
        this.creationDateTo = creationDateTo;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getCatalogversionId() {
        return catalogversionId;
    }

    public void setCatalogversionId(Long catalogversionId) {
        this.catalogversionId = catalogversionId;
    }

    public String getApprovalStatus() {
        return approvalStatus;
    }

    public void setApprovalStatus(String approvalStatus) {
        this.approvalStatus = approvalStatus;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public Long getImageUrlId() {
        return imageUrlId;
    }

    public void setImageUrlId(Long imageUrlId) {
        this.imageUrlId = imageUrlId;
    }

    public Long getThumbnilUrlId() {
        return thumbnilUrlId;
    }

    public void setThumbnilUrlId(Long thumbnilUrlId) {
        this.thumbnilUrlId = thumbnilUrlId;
    }

    public Long getBaseProductId() {
        return baseProductId;
    }

    public void setBaseProductId(Long baseProductId) {
        this.baseProductId = baseProductId;
    }

    public Long getVariantProductId() {
        return variantProductId;
    }

    public void setVariantProductId(Long variantProductId) {
        this.variantProductId = variantProductId;
    }

    public String getProductType() {
        return productType;
    }

    public void setProductType(String productType) {
        this.productType = productType;
    }

    public String getCustomType() {
        return customType;
    }

    public void setCustomType(String customType) {
        this.customType = customType;
    }

    public String getIsSuit() {
        return isSuit;
    }

    public void setIsSuit(String isSuit) {
        this.isSuit = isSuit;
    }

    public String getIsSinSale() {
        return isSinSale;
    }

    public void setIsSinSale(String isSinSale) {
        this.isSinSale = isSinSale;
    }

    public String getSaleStatus() {
        return saleStatus;
    }

    public void setSaleStatus(String saleStatus) {
        this.saleStatus = saleStatus;
    }

    public Long getBrandId() {
        return brandId;
    }

    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }


    public String getProductStatus() {
        return productStatus;
    }

    public void setProductStatus(String productStatus) {
        this.productStatus = productStatus;
    }

    public Date getListingTime() {
        return listingTime;
    }

    public void setListingTime(Date listingTime) {
        this.listingTime = listingTime;
    }

    public Date getDelistingTime() {
        return delistingTime;
    }

    public void setDelistingTime(Date delistingTime) {
        this.delistingTime = delistingTime;
    }

    public String getIsSpeSale() {
        return isSpeSale;
    }

    public void setIsSpeSale(String isSpeSale) {
        this.isSpeSale = isSpeSale;
    }

    public String getOriginCountry() {
        return originCountry;
    }

    public void setOriginCountry(String originCountry) {
        this.originCountry = originCountry;
    }

    public String getSourcePlace() {
        return sourcePlace;
    }

    public void setSourcePlace(String sourcePlace) {
        this.sourcePlace = sourcePlace;
    }

    public BigDecimal getMiniOrderQuantity() {
        return miniOrderQuantity;
    }

    public void setMiniOrderQuantity(BigDecimal miniOrderQuantity) {
        this.miniOrderQuantity = miniOrderQuantity;
    }

    public BigDecimal getRate() {
        return rate;
    }

    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    public String getStype() {
        return stype;
    }

    public void setStype(String stype) {
        this.stype = stype;
    }

    public String getDesignType() {
        return designType;
    }

    public void setDesignType(String designType) {
        this.designType = designType;
    }

    public BigDecimal getpLong() {
        return pLong;
    }

    public void setpLong(BigDecimal pLong) {
        this.pLong = pLong;
    }

    public BigDecimal getpWide() {
        return pWide;
    }

    public void setpWide(BigDecimal pWide) {
        this.pWide = pWide;
    }

    public BigDecimal getpHigh() {
        return pHigh;
    }

    public void setpHigh(BigDecimal pHigh) {
        this.pHigh = pHigh;
    }

    public String getSizeSpecification() {
        return sizeSpecification;
    }

    public void setSizeSpecification(String sizeSpecification) {
        this.sizeSpecification = sizeSpecification;
    }

    public String getSizeUnit() {
        return sizeUnit;
    }

    public void setSizeUnit(String sizeUnit) {
        this.sizeUnit = sizeUnit;
    }

    public BigDecimal getPackingLong() {
        return packingLong;
    }

    public void setPackingLong(BigDecimal packingLong) {
        this.packingLong = packingLong;
    }

    public BigDecimal getPackingWide() {
        return packingWide;
    }

    public void setPackingWide(BigDecimal packingWide) {
        this.packingWide = packingWide;
    }

    public BigDecimal getPackingHigh() {
        return packingHigh;
    }

    public void setPackingHigh(BigDecimal packingHigh) {
        this.packingHigh = packingHigh;
    }

    public String getPackingUnit() {
        return packingUnit;
    }

    public void setPackingUnit(String packingUnit) {
        this.packingUnit = packingUnit;
    }

    public BigDecimal getPackingVolume() {
        return packingVolume;
    }

    public void setPackingVolume(BigDecimal packingVolume) {
        this.packingVolume = packingVolume;
    }

    public String getPackingVolUnit() {
        return packingVolUnit;
    }

    public void setPackingVolUnit(String packingVolUnit) {
        this.packingVolUnit = packingVolUnit;
    }

    public BigDecimal getGrossWeight() {
        return grossWeight;
    }

    public void setGrossWeight(BigDecimal grossWeight) {
        this.grossWeight = grossWeight;
    }

    public BigDecimal getNetWeight() {
        return netWeight;
    }

    public void setNetWeight(BigDecimal netWeight) {
        this.netWeight = netWeight;
    }

    public String getWeightUnit() {
        return weightUnit;
    }

    public void setWeightUnit(String weightUnit) {
        this.weightUnit = weightUnit;
    }

    public String getShape() {
        return shape;
    }

    public void setShape(String shape) {
        this.shape = shape;
    }

    public String getTexture() {
        return texture;
    }

    public void setTexture(String texture) {
        this.texture = texture;
    }

    public String getTextureSpecification() {
        return textureSpecification;
    }

    public void setTextureSpecification(String textureSpecification) {
        this.textureSpecification = textureSpecification;
    }

    public String getMaintainSpecification() {
        return maintainSpecification;
    }

    public void setMaintainSpecification(String maintainSpecification) {
        this.maintainSpecification = maintainSpecification;
    }

    public String getIsResin() {
        return isResin;
    }

    public void setIsResin(String isResin) {
        this.isResin = isResin;
    }

    public BigDecimal getNetCapacity() {
        return netCapacity;
    }

    public void setNetCapacity(BigDecimal netCapacity) {
        this.netCapacity = netCapacity;
    }

    public String getNetCapacityUnit() {
        return netCapacityUnit;
    }

    public void setNetCapacityUnit(String netCapacityUnit) {
        this.netCapacityUnit = netCapacityUnit;
    }

    public String getQgp() {
        return qgp;
    }

    public void setQgp(String qgp) {
        this.qgp = qgp;
    }

    public String getSyncflag() {
        return syncflag;
    }

    public void setSyncflag(String syncflag) {
        this.syncflag = syncflag;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Long getVersionProductId() {
        return versionProductId;
    }

    public void setVersionProductId(Long versionProductId) {
        this.versionProductId = versionProductId;
    }

    public Long getCatalog() {
        return catalog;
    }

    public void setCatalog(Long catalog) {
        this.catalog = catalog;
    }

    public Date getSyncData() {
        return syncData;
    }

    public void setSyncData(Date syncData) {
        this.syncData = syncData;
    }

    public Long getServiceOrderId() {
        return serviceOrderId;
    }

    public void setServiceOrderId(Long serviceOrderId) {
        this.serviceOrderId = serviceOrderId;
    }

    public String getAddFunction1() {
        return addFunction1;
    }

    public void setAddFunction1(String addFunction1) {
        this.addFunction1 = addFunction1;
    }

    public String getAddFunction2() {
        return addFunction2;
    }

    public void setAddFunction2(String addFunction2) {
        this.addFunction2 = addFunction2;
    }

    public String getAddFunction3() {
        return addFunction3;
    }

    public void setAddFunction3(String addFunction3) {
        this.addFunction3 = addFunction3;
    }

    public String getFiller1() {
        return filler1;
    }

    public void setFiller1(String filler1) {
        this.filler1 = filler1;
    }

    public String getFiller2() {
        return filler2;
    }

    public void setFiller2(String filler2) {
        this.filler2 = filler2;
    }

    public String getFiller3() {
        return filler3;
    }

    public void setFiller3(String filler3) {
        this.filler3 = filler3;
    }

    public String getWoodenCrafts1() {
        return woodenCrafts1;
    }

    public void setWoodenCrafts1(String woodenCrafts1) {
        this.woodenCrafts1 = woodenCrafts1;
    }

    public String getWoodenCrafts2() {
        return woodenCrafts2;
    }

    public void setWoodenCrafts2(String woodenCrafts2) {
        this.woodenCrafts2 = woodenCrafts2;
    }

    public String getWoodenCrafts3() {
        return woodenCrafts3;
    }

    public void setWoodenCrafts3(String woodenCrafts3) {
        this.woodenCrafts3 = woodenCrafts3;
    }

    public String getLeatherRange1() {
        return leatherRange1;
    }

    public void setLeatherRange1(String leatherRange1) {
        this.leatherRange1 = leatherRange1;
    }

    public String getLeatherRange2() {
        return leatherRange2;
    }

    public void setLeatherRange2(String leatherRange2) {
        this.leatherRange2 = leatherRange2;
    }

    public String getLeatherRange3() {
        return leatherRange3;
    }

    public void setLeatherRange3(String leatherRange3) {
        this.leatherRange3 = leatherRange3;
    }

    public String getLeatherCraft1() {
        return leatherCraft1;
    }

    public void setLeatherCraft1(String leatherCraft1) {
        this.leatherCraft1 = leatherCraft1;
    }

    public String getLeatherCraft2() {
        return leatherCraft2;
    }

    public void setLeatherCraft2(String leatherCraft2) {
        this.leatherCraft2 = leatherCraft2;
    }

    public String getLeatherCraft3() {
        return leatherCraft3;
    }

    public void setLeatherCraft3(String leatherCraft3) {
        this.leatherCraft3 = leatherCraft3;
    }

    public String getSpecialPrice() {
        return specialPrice;
    }

    public void setSpecialPrice(String specialPrice) {
        this.specialPrice = specialPrice;
    }

    public String getProperty() {
        return property;
    }

    public void setProperty(String property) {
        this.property = property;
    }

    public String getMtart() {
        return mtart;
    }

    public void setMtart(String mtart) {
        this.mtart = mtart;
    }

    public String getMatkl() {
        return matkl;
    }

    public void setMatkl(String matkl) {
        this.matkl = matkl;
    }

    @Override
    public Long getObjectVersionNumber() {
        return objectVersionNumber;
    }

    @Override
    public void setObjectVersionNumber(Long objectVersionNumber) {
        this.objectVersionNumber = objectVersionNumber;
    }

    @Override
    public Long getCreatedBy() {
        return createdBy;
    }

    @Override
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    @Override
    public Long getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    @Override
    public void setLastUpdatedBy(Long lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Override
    public Long getLastUpdateLogin() {
        return lastUpdateLogin;
    }

    @Override
    public void setLastUpdateLogin(Long lastUpdateLogin) {
        this.lastUpdateLogin = lastUpdateLogin;
    }

    public String getIsMain() {
        return isMain;
    }

    public void setIsMain(String isMain) {
        this.isMain = isMain;
    }

    public String getSupplier() {
        return supplier;
    }

    public void setSupplier(String supplier) {
        this.supplier = supplier;
    }

    public String getStyle() {
        return style;
    }

    public void setStyle(String style) {
        this.style = style;
    }

    public List<String> getExcludeProductIds() {
        return excludeProductIds;
    }

    public void setExcludeProductIds(List<String> excludeProductIds) {
        this.excludeProductIds = excludeProductIds;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    public String getDesignElement1() {
        return designElement1;
    }

    public void setDesignElement1(String designElement1) {
        this.designElement1 = designElement1;
    }

    public String getDesignElement2() {
        return designElement2;
    }

    public void setDesignElement2(String designElement2) {
        this.designElement2 = designElement2;
    }

    public String getDesignElement3() {
        return designElement3;
    }

    public void setDesignElement3(String designElement3) {
        this.designElement3 = designElement3;
    }

    public String getFetchImageFlag() {
        return fetchImageFlag;
    }

    public void setFetchImageFlag(String fetchImageFlag) {
        this.fetchImageFlag = fetchImageFlag;
    }


    public String getHascustom() {
        return hascustom;
    }

    public void setHascustom(String hascustom) {
        this.hascustom = hascustom;
    }

    @Override
    public String toString() {
        return "Product{" +
                "productId=" + productId +
                ", code='" + code + '\'' +
                ", name='" + name + '\'' +
                ", catalogversionId=" + catalogversionId +
                ", approvalStatus='" + approvalStatus + '\'' +
                ", unit='" + unit + '\'' +
                ", imageUrlId=" + imageUrlId +
                ", hascustom='" + hascustom + '\'' +
                ", imageUrl='" + imageUrl + '\'' +
                ", serviceOrderId=" + serviceOrderId +
                ", excludeProductIds=" + excludeProductIds +
                ", thumbnilUrlId=" + thumbnilUrlId +
                ", baseProductId=" + baseProductId +
                ", variantProductId=" + variantProductId +
                ", productType='" + productType + '\'' +
                ", customType='" + customType + '\'' +
                ", isSuit='" + isSuit + '\'' +
                ", isSinSale='" + isSinSale + '\'' +
                ", saleStatus='" + saleStatus + '\'' +
                ", brandId=" + brandId +
                ", productStatus='" + productStatus + '\'' +
                ", listingTime=" + listingTime +
                ", delistingTime=" + delistingTime +
                ", isSpeSale='" + isSpeSale + '\'' +
                ", originCountry='" + originCountry + '\'' +
                ", sourcePlace='" + sourcePlace + '\'' +
                ", miniOrderQuantity=" + miniOrderQuantity +
                ", rate=" + rate +
                ", stype='" + stype + '\'' +
                ", designType='" + designType + '\'' +
                ", pLong=" + pLong +
                ", pWide=" + pWide +
                ", pHigh=" + pHigh +
                ", sizeSpecification='" + sizeSpecification + '\'' +
                ", sizeUnit='" + sizeUnit + '\'' +
                ", packingLong=" + packingLong +
                ", packingWide=" + packingWide +
                ", packingHigh=" + packingHigh +
                ", packingUnit='" + packingUnit + '\'' +
                ", packingVolume=" + packingVolume +
                ", packingVolUnit='" + packingVolUnit + '\'' +
                ", grossWeight=" + grossWeight +
                ", netWeight=" + netWeight +
                ", weightUnit='" + weightUnit + '\'' +
                ", shape='" + shape + '\'' +
                ", texture='" + texture + '\'' +
                ", textureSpecification='" + textureSpecification + '\'' +
                ", maintainSpecification='" + maintainSpecification + '\'' +
                ", isResin='" + isResin + '\'' +
                ", netCapacity=" + netCapacity +
                ", netCapacityUnit='" + netCapacityUnit + '\'' +
                ", qgp='" + qgp + '\'' +
                ", syncflag='" + syncflag + '\'' +
                ", creationDate=" + creationDate +
                ", objectVersionNumber=" + objectVersionNumber +
                ", createdBy=" + createdBy +
                ", lastUpdatedBy=" + lastUpdatedBy +
                ", creationDateFrom='" + creationDateFrom + '\'' +
                ", creationDateTo='" + creationDateTo + '\'' +
                ", status='" + status + '\'' +
                ", versionProductId=" + versionProductId +
                ", versionCode='" + versionCode + '\'' +
                ", syncData=" + syncData +
                ", catalog=" + catalog +
                ", basePrice=" + basePrice +
                ", lastUpdateLogin=" + lastUpdateLogin +
                ", lastUpdateDate=" + lastUpdateDate +
                ", catalogversion='" + catalogversion + '\'' +
                ", nameEn='" + nameEn + '\'' +
                ", vProductCode='" + vProductCode + '\'' +
                ", platformCode='" + platformCode + '\'' +
                ", mtart='" + mtart + '\'' +
                ", matkl='" + matkl + '\'' +
                ", rewardProduct='" + rewardProduct + '\'' +
                ", defaultDelivery='" + defaultDelivery + '\'' +
                ", isPreSale='" + isPreSale + '\'' +
                ", mainColor='" + mainColor + '\'' +
                ", isPackaging='" + isPackaging + '\'' +
                ", addFunction1='" + addFunction1 + '\'' +
                ", addFunction2='" + addFunction2 + '\'' +
                ", addFunction3='" + addFunction3 + '\'' +
                ", isStorage='" + isStorage + '\'' +
                ", sofaCombiningForm='" + sofaCombiningForm + '\'' +
                ", isWashable='" + isWashable + '\'' +
                ", filler1='" + filler1 + '\'' +
                ", filler2='" + filler2 + '\'' +
                ", filler3='" + filler3 + '\'' +
                ", suitableUsers='" + suitableUsers + '\'' +
                ", woodenCrafts1='" + woodenCrafts1 + '\'' +
                ", woodenCrafts2='" + woodenCrafts2 + '\'' +
                ", woodenCrafts3='" + woodenCrafts3 + '\'' +
                ", designElement1='" + designElement1 + '\'' +
                ", designElement2='" + designElement2 + '\'' +
                ", designElement3='" + designElement3 + '\'' +
                ", leatherRange1='" + leatherRange1 + '\'' +
                ", leatherRange2='" + leatherRange2 + '\'' +
                ", leatherRange3='" + leatherRange3 + '\'' +
                ", leatherCraft1='" + leatherCraft1 + '\'' +
                ", leatherCraft2='" + leatherCraft2 + '\'' +
                ", leatherCraft3='" + leatherCraft3 + '\'' +
                ", isSoftCushion='" + isSoftCushion + '\'' +
                ", isWheel='" + isWheel + '\'' +
                ", drawerRailNum='" + drawerRailNum + '\'' +
                ", isDamping='" + isDamping + '\'' +
                ", paintCraft='" + paintCraft + '\'' +
                ", drawerNumber='" + drawerNumber + '\'' +
                ", backrestLength='" + backrestLength + '\'' +
                ", isRotate='" + isRotate + '\'' +
                ", specialPrice='" + specialPrice + '\'' +
                ", property='" + property + '\'' +
                ", isMain='" + isMain + '\'' +
                ", filler='" + filler + '\'' +
                ", addFunction='" + addFunction + '\'' +
                ", woodenCrafts='" + woodenCrafts + '\'' +
                ", leatherRange='" + leatherRange + '\'' +
                ", leatherCraft='" + leatherCraft + '\'' +
                ", material='" + material + '\'' +
                ", seriesName='" + seriesName + '\'' +
                ", introduction='" + introduction + '\'' +
                ", salepoint='" + salepoint + '\'' +
                ", supplier='" + supplier + '\'' +
                ", style='" + style + '\'' +
                ", customSupportType='" + customSupportType + '\'' +
                ", customChannelSource='" + customChannelSource + '\'' +
                ", isSuperUsed='" + isSuperUsed + '\'' +
                ", isNormalUsed='" + isNormalUsed + '\'' +
                ", categoryList='" + categoryList + '\'' +
                ", warehouse='" + warehouse + '\'' +
                ", escName='" + escName + '\'' +
                ", normalApproveStatus='" + normalApproveStatus + '\'' +
                ", superApproveStatus='" + superApproveStatus + '\'' +
                ", fetchImageFlag='" + fetchImageFlag + '\'' +
                '}';
    }
}
