package com.hand.hmall.mst.dto;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.math.BigDecimal;

/**
 * Auto Generated By Hap Code Generator
 **/

/**
 * @author xiaoli.yu
 * @version 0.1
 * @name:
 * @Description: 套件映射对象dto
 * @date 2017/7/10 14:37
 */
@ExtensionAttribute(disable = true)
@Table(name = "HMALL_MST_SUITLINE_MAPPING")
public class SuitlineMapping extends BaseDTO {
    /**
     *
     */
    private static final long serialVersionUID = 1241699392427171973L;

    @Id
    @GeneratedValue
    private Long mappingId;

    private Long componentId;

    private BigDecimal quantity;

    private Long productHeadId;

    private String syncflag;

    @Transient
    private Long productId;

    @Transient
    private Long syncProductId;


    //组件编码
    @Transient
    private String code;
    //组件名称
    @Transient
    private String name;

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getMappingId() {
        return mappingId;
    }

    public void setMappingId(Long mappingId) {
        this.mappingId = mappingId;
    }

    public Long getComponentId() {
        return componentId;
    }

    public void setComponentId(Long componentId) {
        this.componentId = componentId;
    }

    public BigDecimal getQuantity() {
        return quantity;
    }

    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    public Long getProductHeadId() {
        return productHeadId;
    }

    public void setProductHeadId(Long productHeadId) {
        this.productHeadId = productHeadId;
    }

    public void setSyncflag(String syncflag) {
        this.syncflag = syncflag;
    }

    public String getSyncflag() {
        return syncflag;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public Long getSyncProductId() {
        return syncProductId;
    }

    public void setSyncProductId(Long syncProductId) {
        this.syncProductId = syncProductId;
    }
}
