package com.hand.hmall.mst.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.*;

/**
 * @author peng.chen
 * @version 0.1
 * @name:
 * @Description: 目录版本配置对象dto
 * @date 2017/7/10 14:37
 */
@ExtensionAttribute(disable = true)
@Table(name = "HMALL_MST_SYNCCONFIG")
public class Syncconfig extends BaseDTO {
    @Id
    @GeneratedValue(generator = GENERATOR_TYPE)
    @Column
    private Long syncconfigId;

    @Column
    private String catalogfrom;

    @Column
    private String versionfrom;

    @Column
    private String catalogto;

    @Column
    private String versionto;

    @Transient
    private String versionName;

    @Transient
    private String versionNameFrom;

    @Transient
    private String versionNameTo;

    public String getVersionNameFrom() {
        return versionNameFrom;
    }

    public void setVersionNameFrom(String versionNameFrom) {
        this.versionNameFrom = versionNameFrom;
    }

    public String getVersionNameTo() {
        return versionNameTo;
    }

    public void setVersionNameTo(String versionNameTo) {
        this.versionNameTo = versionNameTo;
    }

    public String getVersionName() {
        return versionName;
    }

    public void setVersionName(String versionName) {
        this.versionName = versionName;
    }

    public void setSyncconfigId(Long syncconfigId) {
        this.syncconfigId = syncconfigId;
    }

    public Long getSyncconfigId() {
        return syncconfigId;
    }

    public void setCatalogfrom(String catalogfrom) {
        this.catalogfrom = catalogfrom;
    }

    public String getCatalogfrom() {
        return catalogfrom;
    }

    public void setVersionfrom(String versionfrom) {
        this.versionfrom = versionfrom;
    }

    public String getVersionfrom() {
        return versionfrom;
    }

    public void setCatalogto(String catalogto) {
        this.catalogto = catalogto;
    }

    public String getCatalogto() {
        return catalogto;
    }

    public void setVersionto(String versionto) {
        this.versionto = versionto;
    }

    public String getVersionto() {
        return versionto;
    }

}
