package com.hand.hmall.mst.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.*;

/**
 * @author xiaoli.yu
 * @version 0.1
 * @name:
 * @Description: 用户组对象dto
 * @date 2017/7/10 14:37
 */
@ExtensionAttribute(disable = true)
@Table(name = "HMALL_MST_USERGROUP")
public class Usergroup extends BaseDTO {
    /**
     *
     */
    private static final long serialVersionUID = 5854920018624440784L;

    @Id
    @GeneratedValue(generator = GENERATOR_TYPE)
    @Column
    private Long usergroupId;

    @Column
    private String code;

    @Column
    private String name;

    @Column
    private String syncflag;

    @Transient
    private Long userId;


    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public void setUsergroupId(Long usergroupId) {
        this.usergroupId = usergroupId;
    }

    public Long getUsergroupId() {
        return usergroupId;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setSyncflag(String syncflag) {
        this.syncflag = syncflag;
    }

    public String getSyncflag() {
        return syncflag;
    }

}
