package com.hand.hmall.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.*;

@Entity
@Table(name = "HMALL_MST_BUNDLES_MAPPING")
public class MstBundlesMapping {
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY, generator = "select HMALL_MST_BUNDLES_MAPPING_S.nextval from dual")
     @Column
      private Long mappingId;

     @Column
      private Long productId;

     @Column
      private Long bundlesId;

     @Column
      private Long quantity;


     public void setMappingId(Long mappingId){
         this.mappingId = mappingId;
     }

     public Long getMappingId(){
         return mappingId;
     }

     public void setProductId(Long productId){
         this.productId = productId;
     }

     public Long getProductId(){
         return productId;
     }

     public void setBundlesId(Long bundlesId){
         this.bundlesId = bundlesId;
     }

     public Long getBundlesId(){
         return bundlesId;
     }

    public Long getQuantity() {
        return quantity;
    }

    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }
}
