package com.hand.hmall.pin.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Column;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "HMALL_PIN_ALTER")
public class PinAlter extends BaseDTO {
     @Id
     @GeneratedValue(generator = GENERATOR_TYPE)
     @Column
      private Long pinAlterId;

     @Column
      private String eventCode;

     @Column
      private String eventDes;

     @Column
      private String alterLevel1;

     @Column
      private String alterLevel2;

     @Column
      private String alterLevel3;


     public void setPinAlterId(Long pinAlterId){
         this.pinAlterId = pinAlterId;
     }

     public Long getPinAlterId(){
         return pinAlterId;
     }

     public void setEventCode(String eventCode){
         this.eventCode = eventCode;
     }

     public String getEventCode(){
         return eventCode;
     }

     public void setEventDes(String eventDes){
         this.eventDes = eventDes;
     }

     public String getEventDes(){
         return eventDes;
     }

     public void setAlterLevel1(String alterLevel1){
         this.alterLevel1 = alterLevel1;
     }

     public String getAlterLevel1(){
         return alterLevel1;
     }

     public void setAlterLevel2(String alterLevel2){
         this.alterLevel2 = alterLevel2;
     }

     public String getAlterLevel2(){
         return alterLevel2;
     }

     public void setAlterLevel3(String alterLevel3){
         this.alterLevel3 = alterLevel3;
     }

     public String getAlterLevel3(){
         return alterLevel3;
     }

     }
