package com.hand.hmall.mst.service;

import com.hand.hap.core.ProxySelf;
import com.hand.hap.system.service.IBaseService;
import com.hand.hmall.mst.dto.Basestore;
/**
 * Auto Generated By Hap Code Generator
 *
 * @author xiaoli.yu
 * @version 0.1
 * @name:
 * @Description: 商铺对象service接口
 * @date 2017/7/20 16:05
 */
public interface IBasestoreService extends IBaseService<Basestore>, ProxySelf<IBasestoreService>{

}