package com.hand.hmall.mst.mapper;

import com.hand.hap.mybatis.common.Mapper;
import com.hand.hmall.mst.dto.Basestore;
/**
 * Auto Generated By Hap Code Generator
 *
 * @author xiaoli.yu
 * @version 0.1
 * @name:
 * @Description: 商铺对象Mapper
 * @date 2017/7/20 16:05
 */
public interface BasestoreMapper extends Mapper<Basestore>{

}