package com.hand.hmall.as.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.*;
import java.math.BigDecimal;

/**
 * @author xuxiaoxue
 * @version 0.1
 * @name AsCompensateEntry
 * @description 销售赔付单行DTO类
 * @date 2017/10/11
 */
@ExtensionAttribute(disable = true)
@Table(name = "HMALL_AS_COMPENSATE_ENTRY")
public class AsCompensateEntry extends BaseDTO {
    @Id
    @GeneratedValue(generator = GENERATOR_TYPE)
    @Column
    private Long compensateEntryId;

    @Column
    private Long compensateId;

    @Column
    private String lineNumber;

    @Column
    private String compensateType;

    @Column
    private Double quantity;

    @Column
    private String unit;

    @Column
    private BigDecimal unitFee;

    @Column
    private BigDecimal totalFee;

    @Column
    private String note;
    @Transient
    private String sapCode;


    public void setCompensateEntryId(Long compensateEntryId) {
        this.compensateEntryId = compensateEntryId;
    }

    public Long getCompensateEntryId() {
        return compensateEntryId;
    }

    public void setCompensateId(Long compensateId) {
        this.compensateId = compensateId;
    }

    public Long getCompensateId() {
        return compensateId;
    }

    public void setLineNumber(String lineNumber) {
        this.lineNumber = lineNumber;
    }

    public String getLineNumber() {
        return lineNumber;
    }

    public void setCompensateType(String compensateType) {
        this.compensateType = compensateType;
    }

    public String getCompensateType() {
        return compensateType;
    }

    public Double getQuantity() {
        return quantity;
    }

    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }

    public BigDecimal getUnitFee() {
        return unitFee;
    }

    public void setUnitFee(BigDecimal unitFee) {
        this.unitFee = unitFee;
    }

    public BigDecimal getTotalFee() {
        return totalFee;
    }

    public void setTotalFee(BigDecimal totalFee) {
        this.totalFee = totalFee;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getUnit() {
        return unit;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getNote() {
        return note;
    }

    public String getSapCode() {
        return sapCode;
    }

    public void setSapCode(String sapCode) {
        this.sapCode = sapCode;
    }
}
