package com.hand.hmall.as.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "HMALL_AS_SERVICEORDER_ENTRY")
public class AsDispatchorderEntry extends BaseDTO {
    @Id
    @GeneratedValue(generator = GENERATOR_TYPE)
    @Column
    private Long serviceOrderEntryId;

    @Column
    private Long serviceOrderId;

    @Column
    private Long consignmentId;

    @Column
    private String code;

    @Column
    private Long lineNumber;

    @Column
    private Long parentLine;

    @Column
    private Long quantity;

    @Column
    private String unit;

    @Column
    private Long basePrice;

    @Column
    private Long discountFee;

    @Column
    private Long discountFeel;

    @Column
    private Long unitFee;

    @Column
    private Long totalFee;

    @Column
    private String isGift;

    @Column
    private Date estimateDeliveryTime;

    @Column
    private Date estimateConTime;

    @Column
    private Long productId;

    @Column
    private String vproductCode;

    @Column
    private String sutiCode;

    @Column
    private String orderEntryType;

    @Column
    private String pin;

    @Column
    private Long shippingFee;

    @Column
    private Long installationFee;

    @Column
    private String syncflag;

    @Column
    private String shippingType;

    @Column
    private Long pointOfServiceId;

    @Column
    private String bomApproved;

    @Column
    private String note;

    @Column
    private Long objectVersionNumber;

    @Column
    private BigDecimal preShippingfee;

    @Column
    private BigDecimal preInstallationfee;

    @Column
    private String reason1;

    @Column
    private String reason1Des;

    @Column
    private String reason2;

    @Column
    private String reason2Des;

    @Transient
    private String name;

    public String getBomApproved() {
        return bomApproved;
    }

    public void setBomApproved(String bomApproved) {
        this.bomApproved = bomApproved;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    @Override
    public Long getObjectVersionNumber() {
        return objectVersionNumber;
    }

    @Override
    public void setObjectVersionNumber(Long objectVersionNumber) {
        this.objectVersionNumber = objectVersionNumber;
    }

    public BigDecimal getPreShippingfee() {
        return preShippingfee;
    }

    public void setPreShippingfee(BigDecimal preShippingfee) {
        this.preShippingfee = preShippingfee;
    }

    public BigDecimal getPreInstallationfee() {
        return preInstallationfee;
    }

    public void setPreInstallationfee(BigDecimal preInstallationfee) {
        this.preInstallationfee = preInstallationfee;
    }

    public String getReason1() {
        return reason1;
    }

    public void setReason1(String reason1) {
        this.reason1 = reason1;
    }

    public String getReason1Des() {
        return reason1Des;
    }

    public void setReason1Des(String reason1Des) {
        this.reason1Des = reason1Des;
    }

    public String getReason2() {
        return reason2;
    }

    public void setReason2(String reason2) {
        this.reason2 = reason2;
    }

    public String getReason2Des() {
        return reason2Des;
    }

    public void setReason2Des(String reason2Des) {
        this.reason2Des = reason2Des;
    }

    public void setServiceOrderEntryId(Long serviceOrderEntryId) {
        this.serviceOrderEntryId = serviceOrderEntryId;
    }

    public Long getServiceOrderEntryId() {
        return serviceOrderEntryId;
    }

    public void setServiceOrderId(Long serviceOrderId) {
        this.serviceOrderId = serviceOrderId;
    }

    public Long getServiceOrderId() {
        return serviceOrderId;
    }

    public void setConsignmentId(Long consignmentId) {
        this.consignmentId = consignmentId;
    }

    public Long getConsignmentId() {
        return consignmentId;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }

    public void setLineNumber(Long lineNumber) {
        this.lineNumber = lineNumber;
    }

    public Long getLineNumber() {
        return lineNumber;
    }

    public void setParentLine(Long parentLine) {
        this.parentLine = parentLine;
    }

    public Long getParentLine() {
        return parentLine;
    }

    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    public Long getQuantity() {
        return quantity;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getUnit() {
        return unit;
    }

    public void setBasePrice(Long basePrice) {
        this.basePrice = basePrice;
    }

    public Long getBasePrice() {
        return basePrice;
    }

    public void setDiscountFee(Long discountFee) {
        this.discountFee = discountFee;
    }

    public Long getDiscountFee() {
        return discountFee;
    }

    public void setDiscountFeel(Long discountFeel) {
        this.discountFeel = discountFeel;
    }

    public Long getDiscountFeel() {
        return discountFeel;
    }

    public void setUnitFee(Long unitFee) {
        this.unitFee = unitFee;
    }

    public Long getUnitFee() {
        return unitFee;
    }

    public void setTotalFee(Long totalFee) {
        this.totalFee = totalFee;
    }

    public Long getTotalFee() {
        return totalFee;
    }

    public void setIsGift(String isGift) {
        this.isGift = isGift;
    }

    public String getIsGift() {
        return isGift;
    }

    public void setEstimateDeliveryTime(Date estimateDeliveryTime) {
        this.estimateDeliveryTime = estimateDeliveryTime;
    }

    public Date getEstimateDeliveryTime() {
        return estimateDeliveryTime;
    }

    public void setEstimateConTime(Date estimateConTime) {
        this.estimateConTime = estimateConTime;
    }

    public Date getEstimateConTime() {
        return estimateConTime;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public Long getProductId() {
        return productId;
    }

    public void setVproductCode(String vproductCode) {
        this.vproductCode = vproductCode;
    }

    public String getVproductCode() {
        return vproductCode;
    }

    public void setSutiCode(String sutiCode) {
        this.sutiCode = sutiCode;
    }

    public String getSutiCode() {
        return sutiCode;
    }

    public void setOrderEntryType(String orderEntryType) {
        this.orderEntryType = orderEntryType;
    }

    public String getOrderEntryType() {
        return orderEntryType;
    }

    public void setPin(String pin) {
        this.pin = pin;
    }

    public String getPin() {
        return pin;
    }

    public void setShippingFee(Long shippingFee) {
        this.shippingFee = shippingFee;
    }

    public Long getShippingFee() {
        return shippingFee;
    }

    public void setInstallationFee(Long installationFee) {
        this.installationFee = installationFee;
    }

    public Long getInstallationFee() {
        return installationFee;
    }

    public void setSyncflag(String syncflag) {
        this.syncflag = syncflag;
    }

    public String getSyncflag() {
        return syncflag;
    }

    public void setShippingType(String shippingType) {
        this.shippingType = shippingType;
    }

    public String getShippingType() {
        return shippingType;
    }

    public void setPointOfServiceId(Long pointOfServiceId) {
        this.pointOfServiceId = pointOfServiceId;
    }

    public Long getPointOfServiceId() {
        return pointOfServiceId;
    }

    public String getName() { return name; }

    public void setName(String name) { this.name = name; }
}
