package com.hand.hmall.as.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.*;

@ExtensionAttribute(disable = true)
@Table(name = "HMALL_AS_RETURN_ENTRY")
public class AsReturnEntry extends BaseDTO {
    @Id
    @GeneratedValue(generator = GENERATOR_TYPE)
    @Column
    private Long asReturnEntryId;

    @Column
    private Long asReturnId;

    @Column
    private Long orderEntryId;

    @Column
    private Long serviceOrderId;

    @Column
    private String lineNumber;

    @Column
    private Long parentLine;

    @Column
    private Double returnFee;

    @Column
    private Long quantity;

    @Column
    private String unit;

    @Column
    private Double basePrice;

    @Column
    private String isGift;

    @Column
    private String productId;

    @Column
    private String vproduct;

    @Column
    private String suitCode;

    @Column
    private String pin;

    @Column
    private String shippingType;

    @Column
    private String note;

    @Column
    private String returnReason1;

    @Column
    private String returnReason2;

    @Transient
    private String returnEntryStatus;

    @Transient
    private String parentLineNumber;

    @Transient
    private String entryReturnType;

    @Transient
    private String productCode;

    @Transient
    private String entryPointOfService;

    @Transient
    private String entrySapCode;

    @Transient
    private String entryOrderLineNumber;

    @Transient
    private String tradeFinishTime;

    @Transient
    private String vCode;

    @Transient
    private String customerMsg;

    @Transient
    private String productSize;

    @Transient
    private String productPackedSize;

    @Transient
    private String code;

    @Transient
    private String name;

    @Transient
    private String orderId;

    @Transient
    private String vproductCode;

    @Column
    private Double internalPrice;

    @Transient
    private String vtweg;

    @Column
    private String returnentryStatus;

    public String getReturnentryStatus() {
        return returnentryStatus;
    }

    public void setReturnentryStatus(String returnentryStatus) {
        this.returnentryStatus = returnentryStatus;
    }

    public Double getInternalPrice() {
        return internalPrice;
    }

    public void setInternalPrice(Double internalPrice) {
        this.internalPrice = internalPrice;
    }

    public String getVproductCode() {
        return vproductCode;
    }

    public void setVproductCode(String vproductCode) {
        this.vproductCode = vproductCode;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public void setAsReturnEntryId(Long asReturnEntryId) {
        this.asReturnEntryId = asReturnEntryId;
    }

    public Long getAsReturnEntryId() {
        return asReturnEntryId;
    }

    public Long getAsReturnId() {
        return asReturnId;
    }

    public void setAsReturnId(Long asReturnId) {
        this.asReturnId = asReturnId;
    }

    public void setOrderEntryId(Long orderEntryId) {
        this.orderEntryId = orderEntryId;
    }

    public Long getOrderEntryId() {
        return orderEntryId;
    }

    public void setServiceOrderId(Long serviceOrderId) {
        this.serviceOrderId = serviceOrderId;
    }

    public Long getServiceOrderId() {
        return serviceOrderId;
    }

    public void setLineNumber(String lineNumber) {
        this.lineNumber = lineNumber;
    }

    public String getLineNumber() {
        return lineNumber;
    }

    public Long getParentLine() {
        return parentLine;
    }

    public void setParentLine(Long parentLine) {
        this.parentLine = parentLine;
    }

    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    public Long getQuantity() {
        return quantity;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getUnit() {
        return unit;
    }

    public Double getBasePrice() {
        return basePrice;
    }

    public void setBasePrice(Double basePrice) {
        this.basePrice = basePrice;
    }

    public void setIsGift(String isGift) {
        this.isGift = isGift;
    }

    public String getIsGift() {
        return isGift;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getProductId() {
        return productId;
    }

    public void setVproduct(String vproduct) {
        this.vproduct = vproduct;
    }

    public String getVproduct() {
        return vproduct;
    }

    public void setSuitCode(String suitCode) {
        this.suitCode = suitCode;
    }

    public String getSuitCode() {
        return suitCode;
    }

    public void setPin(String pin) {
        this.pin = pin;
    }

    public String getPin() {
        return pin;
    }

    public void setShippingType(String shippingType) {
        this.shippingType = shippingType;
    }

    public String getShippingType() {
        return shippingType;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getNote() {
        return note;
    }

    public void setReturnReason1(String returnReason1) {
        this.returnReason1 = returnReason1;
    }

    public String getReturnReason1() {
        return returnReason1;
    }

    public void setReturnReason2(String returnReason2) {
        this.returnReason2 = returnReason2;
    }

    public String getReturnReason2() {
        return returnReason2;
    }

    public String getParentLineNumber() {
        return parentLineNumber;
    }

    public void setParentLineNumber(String parentLineNumber) {
        this.parentLineNumber = parentLineNumber;
    }

    public String getEntryReturnType() {
        return entryReturnType;
    }

    public void setEntryReturnType(String entryReturnType) {
        this.entryReturnType = entryReturnType;
    }

    public String getProductCode() {
        return productCode;
    }

    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    public String getEntryPointOfService() {
        return entryPointOfService;
    }

    public void setEntryPointOfService(String entryPointOfService) {
        this.entryPointOfService = entryPointOfService;
    }

    public String getEntrySapCode() {
        return entrySapCode;
    }

    public void setEntrySapCode(String entrySapCode) {
        this.entrySapCode = entrySapCode;
    }

    public String getEntryOrderLineNumber() {
        return entryOrderLineNumber;
    }

    public void setEntryOrderLineNumber(String entryOrderLineNumber) {
        this.entryOrderLineNumber = entryOrderLineNumber;
    }

    public String getTradeFinishTime() {
        return tradeFinishTime;
    }

    public void setTradeFinishTime(String tradeFinishTime) {
        this.tradeFinishTime = tradeFinishTime;
    }

    public String getvCode() {
        return vCode;
    }

    public void setvCode(String vCode) {
        this.vCode = vCode;
    }

    public String getCustomerMsg() {
        return customerMsg;
    }

    public void setCustomerMsg(String customerMsg) {
        this.customerMsg = customerMsg;
    }

    public Double getReturnFee() {
        return returnFee;
    }

    public void setReturnFee(Double returnFee) {
        this.returnFee = returnFee;
    }

    public String getProductSize() {
        return productSize;
    }

    public void setProductSize(String productSize) {
        this.productSize = productSize;
    }

    public String getProductPackedSize() {
        return productPackedSize;
    }

    public void setProductPackedSize(String productPackedSize) {
        this.productPackedSize = productPackedSize;
    }

    public String getReturnEntryStatus() {
        return returnEntryStatus;
    }

    public void setReturnEntryStatus(String returnEntryStatus) {
        this.returnEntryStatus = returnEntryStatus;
    }

    public String getVtweg() {
        return vtweg;
    }

    public void setVtweg(String vtweg) {
        this.vtweg = vtweg;
    }
}
