package com.hand.hmall.as.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@ExtensionAttribute(disable = true)
@Table(name = "HMALL_AS_EXCHANGE")
public class Exchange extends BaseDTO {
    @Id
    @GeneratedValue(generator = GENERATOR_TYPE)
    @Column
    private Long asExchangeId;

    @Column
    private String code;

    @Column
    private String status;

    @Column
    private Long serviceOrderId;

    @Column
    private Long orderId;

    @Column
    private String note;

    @Column
    private String name;

    @Column
    private String mobile;

    @Column
    private String address;

    @Column
    private String cs;

    @Column
    private Date finishTime;

    @Column
    private String syncflag;

    @Column
    private Date appointmentDate;

    @Column
    private Date executionDate;

    @Column
    private Long transFee;

    @Column
    private Long restoreFee;

    @Column
    private Long packageFee;

    @Column
    private Long installFee;

    @Column
    private Long preOrderFee;

    @Column
    private Long afterChangeFee;

    @Column
    private Long finalFee;


    public void setAsExchangeId(Long asExchangeId) {
        this.asExchangeId = asExchangeId;
    }

    public Long getAsExchangeId() {
        return asExchangeId;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStatus() {
        return status;
    }

    public void setServiceOrderId(Long serviceOrderId) {
        this.serviceOrderId = serviceOrderId;
    }

    public Long getServiceOrderId() {
        return serviceOrderId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public Long getOrderId() {
        return orderId;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getNote() {
        return note;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getMobile() {
        return mobile;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getAddress() {
        return address;
    }

    public void setCs(String cs) {
        this.cs = cs;
    }

    public String getCs() {
        return cs;
    }

    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    public Date getFinishTime() {
        return finishTime;
    }

    public void setSyncflag(String syncflag) {
        this.syncflag = syncflag;
    }

    public String getSyncflag() {
        return syncflag;
    }

    public void setAppointmentDate(Date appointmentDate) {
        this.appointmentDate = appointmentDate;
    }

    public Date getAppointmentDate() {
        return appointmentDate;
    }

    public void setExecutionDate(Date executionDate) {
        this.executionDate = executionDate;
    }

    public Date getExecutionDate() {
        return executionDate;
    }

    public void setTransFee(Long transFee) {
        this.transFee = transFee;
    }

    public Long getTransFee() {
        return transFee;
    }

    public void setRestoreFee(Long restoreFee) {
        this.restoreFee = restoreFee;
    }

    public Long getRestoreFee() {
        return restoreFee;
    }

    public void setPackageFee(Long packageFee) {
        this.packageFee = packageFee;
    }

    public Long getPackageFee() {
        return packageFee;
    }

    public void setInstallFee(Long installFee) {
        this.installFee = installFee;
    }

    public Long getInstallFee() {
        return installFee;
    }

    public void setPreOrderFee(Long preOrderFee) {
        this.preOrderFee = preOrderFee;
    }

    public Long getPreOrderFee() {
        return preOrderFee;
    }

    public void setAfterChangeFee(Long afterChangeFee) {
        this.afterChangeFee = afterChangeFee;
    }

    public Long getAfterChangeFee() {
        return afterChangeFee;
    }

    public void setFinalFee(Long finalFee) {
        this.finalFee = finalFee;
    }

    public Long getFinalFee() {
        return finalFee;
    }

}
