package com.hand.hmall.as.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable = true)
@Table(name = "HMALL_AS_EXCHANGE_ENTRY")
public class ExchangeEntry extends BaseDTO {
    @Id
    @GeneratedValue(generator = GENERATOR_TYPE)
    @Column
    private Long asExchangeEntryId;

    @Column
    private String exchangeOrderId;

    @Column
    private Long orderId;

    @Column
    private Long serviceOrderId;

    @Column
    private String lineNumber;

    @Column
    private String parentLine;

    @Column
    private Long quantity;

    @Column
    private String unit;

    @Column
    private Long basePrice;

    @Column
    private Long unitFee;

    @Column
    private Long totalFee;

    @Column
    private String isGift;

    @Column
    private String productId;

    @Column
    private String vproduct;

    @Column
    private String suitCode;

    @Column
    private String pin;

    @Column
    private String shippingType;

    @Column
    private String note;

    @Column
    private String returnReason1;

    @Column
    private String returnReason2;

    @Column
    private String entryCategory;


    public void setAsExchangeEntryId(Long asExchangeEntryId) {
        this.asExchangeEntryId = asExchangeEntryId;
    }

    public Long getAsExchangeEntryId() {
        return asExchangeEntryId;
    }

    public void setExchangeOrderId(String exchangeOrderId) {
        this.exchangeOrderId = exchangeOrderId;
    }

    public String getExchangeOrderId() {
        return exchangeOrderId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    public Long getOrderId() {
        return orderId;
    }

    public void setServiceOrderId(Long serviceOrderId) {
        this.serviceOrderId = serviceOrderId;
    }

    public Long getServiceOrderId() {
        return serviceOrderId;
    }

    public void setLineNumber(String lineNumber) {
        this.lineNumber = lineNumber;
    }

    public String getLineNumber() {
        return lineNumber;
    }

    public void setParentLine(String parentLine) {
        this.parentLine = parentLine;
    }

    public String getParentLine() {
        return parentLine;
    }

    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    public Long getQuantity() {
        return quantity;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getUnit() {
        return unit;
    }

    public void setBasePrice(Long basePrice) {
        this.basePrice = basePrice;
    }

    public Long getBasePrice() {
        return basePrice;
    }

    public void setUnitFee(Long unitFee) {
        this.unitFee = unitFee;
    }

    public Long getUnitFee() {
        return unitFee;
    }

    public void setTotalFee(Long totalFee) {
        this.totalFee = totalFee;
    }

    public Long getTotalFee() {
        return totalFee;
    }

    public void setIsGift(String isGift) {
        this.isGift = isGift;
    }

    public String getIsGift() {
        return isGift;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getProductId() {
        return productId;
    }

    public void setVproduct(String vproduct) {
        this.vproduct = vproduct;
    }

    public String getVproduct() {
        return vproduct;
    }

    public void setSuitCode(String suitCode) {
        this.suitCode = suitCode;
    }

    public String getSuitCode() {
        return suitCode;
    }

    public void setPin(String pin) {
        this.pin = pin;
    }

    public String getPin() {
        return pin;
    }

    public void setShippingType(String shippingType) {
        this.shippingType = shippingType;
    }

    public String getShippingType() {
        return shippingType;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getNote() {
        return note;
    }

    public void setReturnReason1(String returnReason1) {
        this.returnReason1 = returnReason1;
    }

    public String getReturnReason1() {
        return returnReason1;
    }

    public void setReturnReason2(String returnReason2) {
        this.returnReason2 = returnReason2;
    }

    public String getReturnReason2() {
        return returnReason2;
    }

    public void setEntryCategory(String entryCategory) {
        this.entryCategory = entryCategory;
    }

    public String getEntryCategory() {
        return entryCategory;
    }

}
