package com.hand.hmall.as.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.*;
import java.util.Date;
import java.util.List;

@ExtensionAttribute(disable = true)
@Table(name = "HMALL_AS_SERVICEORDER_ENTRY")
public class ServiceorderEntry extends BaseDTO {
    @Id
    @GeneratedValue(generator = GENERATOR_TYPE)
    @Column
    private Long serviceOrderEntryId;

    @Column
    private Long orderEntryId;

    @Column
    private Long serviceOrderId;

    @Column
    private Long consignmentId;

    @Column
    private String code;

    @Column
    private Long lineNumber;

    @Column
    private Long parentLine;

    @Column
    private Long quantity;

    @Column
    private String unit;

    @Column
    private Long basePrice;

    @Column
    private Long discountFee;

    @Column
    private Long discountFeel;

    @Column
    private Long unitFee;

    @Column
    private Long totalFee;

    @Column
    private String isGift;

    @Column
    private Date estimateDeliveryTime;

    @Column
    private Date estimateConTime;

    @Column
    private Long productId;

    @Column
    private String vproductCode;

    @Column
    private String sutiCode;

    @Column
    private String orderEntryType;

    @Column
    private String pin;

    @Column
    private Long shippingFee;

    @Column
    private Long installationFee;

    @Column
    private String syncflag;

    @Column
    private String shippingType;

    @Column
    private Long pointOfServiceId;

    @Column
    private String note;

    @Column
    private String bomApproved;

    @Column
    private Long preShippingfee;

    @Column
    private Long preInstallationfee;

    @Column
    private String svproReason1;

    @Column
    private String svproReason2;

    @Column
    private String reproReason1;

    @Column
    private String reproReason2;

    @Column
    private String returnReason1;

    @Column
    private String returnReason2;

    @Column
    private Long refundFee;

    @Column
    private Long refundSum;

    @Transient
    private String productCode;

    @Transient
    private String productName;

    @Transient
    private String orderCode;

    @Transient
    private String consignmentCode;

    @Transient
    private String name;
    @Transient
    private List<String> excludeProductIds;//剔除不想要的产品

    @Transient
    private String status; //服务单行关联的发货单状态

    @Transient
    private Long orderEntryQuantity; //服务单行关联的订单行中的数量

    @Transient
    private Double orderEntryUnitFee; //服务单行关联的订单行中的unitFee

    public Double getOrderEntryUnitFee() {
        return orderEntryUnitFee;
    }

    public void setOrderEntryUnitFee(Double orderEntryUnitFee) {
        this.orderEntryUnitFee = orderEntryUnitFee;
    }

    public Long getOrderEntryQuantity() {
        return orderEntryQuantity;
    }

    public void setOrderEntryQuantity(Long orderEntryQuantity) {
        this.orderEntryQuantity = orderEntryQuantity;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getSvproReason1() {
        return svproReason1;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getOrderCode() {
        return orderCode;
    }

    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    public String getConsignmentCode() {
        return consignmentCode;
    }

    public void setConsignmentCode(String consignmentCode) {
        this.consignmentCode = consignmentCode;
    }

    public Long getRefundFee() {
        return refundFee;
    }

    public void setRefundFee(Long refundFee) {
        this.refundFee = refundFee;
    }

    public Long getRefundSum() {
        return refundSum;
    }

    public void setRefundSum(Long refundSum) {
        this.refundSum = refundSum;
    }

    public String getProductCode() {
        return productCode;
    }

    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getName() {
        return name;
    }

    public void setSvproReason1(String svproReason1) {
        this.svproReason1 = svproReason1;
    }

    public String getSvproReason2() {
        return svproReason2;
    }

    public void setSvproReason2(String svproReason2) {
        this.svproReason2 = svproReason2;
    }

    public String getReproReason1() {
        return reproReason1;
    }

    public void setReproReason1(String reproReason1) {
        this.reproReason1 = reproReason1;
    }

    public String getReproReason2() {
        return reproReason2;
    }

    public void setReproReason2(String reproReason2) {
        this.reproReason2 = reproReason2;
    }

    public String getReturnReason1() {
        return returnReason1;
    }

    public void setReturnReason1(String returnReason1) {
        this.returnReason1 = returnReason1;
    }

    public String getReturnReason2() {
        return returnReason2;
    }

    public void setReturnReason2(String returnReason2) {
        this.returnReason2 = returnReason2;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getBomApproved() {
        return bomApproved;
    }

    public void setBomApproved(String bomApproved) {
        this.bomApproved = bomApproved;
    }

    public Long getPreShippingfee() {
        return preShippingfee;
    }

    public void setPreShippingfee(Long preShippingfee) {
        this.preShippingfee = preShippingfee;
    }

    public Long getPreInstallationfee() {
        return preInstallationfee;
    }

    public void setPreInstallationfee(Long preInstallationfee) {
        this.preInstallationfee = preInstallationfee;
    }

    public void setServiceOrderEntryId(Long serviceOrderEntryId) {
        this.serviceOrderEntryId = serviceOrderEntryId;
    }

    public Long getServiceOrderEntryId() {
        return serviceOrderEntryId;
    }

    public void setServiceOrderId(Long serviceOrderId) {
        this.serviceOrderId = serviceOrderId;
    }

    public Long getServiceOrderId() {
        return serviceOrderId;
    }

    public void setConsignmentId(Long consignmentId) {
        this.consignmentId = consignmentId;
    }

    public Long getConsignmentId() {
        return consignmentId;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }

    public void setLineNumber(Long lineNumber) {
        this.lineNumber = lineNumber;
    }

    public Long getLineNumber() {
        return lineNumber;
    }

    public void setParentLine(Long parentLine) {
        this.parentLine = parentLine;
    }

    public Long getParentLine() {
        return parentLine;
    }

    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    public Long getQuantity() {
        return quantity;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getUnit() {
        return unit;
    }

    public void setBasePrice(Long basePrice) {
        this.basePrice = basePrice;
    }

    public Long getBasePrice() {
        return basePrice;
    }

    public void setDiscountFee(Long discountFee) {
        this.discountFee = discountFee;
    }

    public Long getDiscountFee() {
        return discountFee;
    }

    public void setDiscountFeel(Long discountFeel) {
        this.discountFeel = discountFeel;
    }

    public Long getDiscountFeel() {
        return discountFeel;
    }

    public void setUnitFee(Long unitFee) {
        this.unitFee = unitFee;
    }

    public Long getUnitFee() {
        return unitFee;
    }

    public void setTotalFee(Long totalFee) {
        this.totalFee = totalFee;
    }

    public Long getTotalFee() {
        return totalFee;
    }

    public void setIsGift(String isGift) {
        this.isGift = isGift;
    }

    public String getIsGift() {
        return isGift;
    }

    public void setEstimateDeliveryTime(Date estimateDeliveryTime) {
        this.estimateDeliveryTime = estimateDeliveryTime;
    }

    public Date getEstimateDeliveryTime() {
        return estimateDeliveryTime;
    }

    public void setEstimateConTime(Date estimateConTime) {
        this.estimateConTime = estimateConTime;
    }

    public Date getEstimateConTime() {
        return estimateConTime;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public Long getProductId() {
        return productId;
    }

    public void setVproductCode(String vproductCode) {
        this.vproductCode = vproductCode;
    }

    public String getVproductCode() {
        return vproductCode;
    }

    public void setSutiCode(String sutiCode) {
        this.sutiCode = sutiCode;
    }

    public String getSutiCode() {
        return sutiCode;
    }

    public void setOrderEntryType(String orderEntryType) {
        this.orderEntryType = orderEntryType;
    }

    public String getOrderEntryType() {
        return orderEntryType;
    }

    public void setPin(String pin) {
        this.pin = pin;
    }

    public String getPin() {
        return pin;
    }

    public void setShippingFee(Long shippingFee) {
        this.shippingFee = shippingFee;
    }

    public Long getShippingFee() {
        return shippingFee;
    }

    public void setInstallationFee(Long installationFee) {
        this.installationFee = installationFee;
    }

    public Long getInstallationFee() {
        return installationFee;
    }

    public void setSyncflag(String syncflag) {
        this.syncflag = syncflag;
    }

    public String getSyncflag() {
        return syncflag;
    }

    public void setShippingType(String shippingType) {
        this.shippingType = shippingType;
    }

    public String getShippingType() {
        return shippingType;
    }

    public void setPointOfServiceId(Long pointOfServiceId) {
        this.pointOfServiceId = pointOfServiceId;
    }

    public Long getPointOfServiceId() {
        return pointOfServiceId;
    }

    public List<String> getExcludeProductIds() {
        return excludeProductIds;
    }

    public void setExcludeProductIds(List<String> excludeProductIds) {
        this.excludeProductIds = excludeProductIds;
    }

    public Long getOrderEntryId() {
        return orderEntryId;
    }

    public void setOrderEntryId(Long orderEntryId) {
        this.orderEntryId = orderEntryId;
    }
}
