package com.hand.promotion.dto;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Auto Generated By Hap Code Generator
 **/

@Table(name = "HMALL_MST_CATEGORY")
public class MstCategory {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY, generator = "select HMALL_MST_CATEGORY_S.nextval from dual")
    @Column
    private Long categoryId;

    @Column
    private String categoryCode;

    @Column
    private String categoryName;

    @Column
    private Long catalogVersion;

    @Column
    private String categoryLevel;

    @Column
    private String syncflag;


    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    public Long getCategoryId() {
        return categoryId;
    }

    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode;
    }

    public String getCategoryCode() {
        return categoryCode;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public void setCatalogVersion(Long catalogVersion) {
        this.catalogVersion = catalogVersion;
    }

    public Long getCatalogVersion() {
        return catalogVersion;
    }

    public void setCategoryLevel(String categoryLevel) {
        this.categoryLevel = categoryLevel;
    }

    public String getCategoryLevel() {
        return categoryLevel;
    }

    public void setSyncflag(String syncflag) {
        this.syncflag = syncflag;
    }

    public String getSyncflag() {
        return syncflag;
    }

}
