package com.hand.hmall.mst.service.impl;

import com.hand.hap.system.service.impl.BaseServiceImpl;
import com.hand.hmall.mst.dto.Basestore;
import com.hand.hmall.mst.service.IBasestoreService;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
/**
 * Auto Generated By Hap Code Generator
 *
 * @author xiaoli.yu
 * @version 0.1
 * @name:
 * @Description: 商铺对象service实现类
 * @date 2017/7/20 16:05
 */
@Service
@Transactional
public class BasestoreServiceImpl extends BaseServiceImpl<Basestore> implements IBasestoreService{

}